apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-test-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: kind-registry:5000/streamnativeio/function-mesh-catalog:v0.19.0-rc-1
