apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app: function-mesh-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app: function-mesh-operator
  replicas: 1
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: '9443'
      labels:
        control-plane: controller-manager
        app: function-mesh-operator
        service.istio.io/canonical-name: function-mesh-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --namespaced-backend-config=backend-config
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 20Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
