apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "compute.functionmesh.io/v1alpha1",
          "kind": "FunctionMesh",
          "metadata": {
            "name": "functionmesh-sample"
          },
          "spec": {
            "functions": [
              {
                "autoAck": true,
                "className": "org.apache.pulsar.functions.api.examples.ExclamationFunction",
                "clusterName": "test-pulsar",
                "forwardSourceMessageProperty": true,
                "input": {
                  "topics": [
                    "persistent://public/default/functionmesh-input-topic"
                  ]
                },
                "java": {
                  "jar": "pulsar-functions-api-examples.jar",
                  "jarLocation": "public/default/nlu-test-functionmesh-ex1"
                },
                "logTopic": "persistent://public/default/logging-function-log",
                "maxReplicas": 1,
                "name": "ex1",
                "output": {
                  "topic": "persistent://public/default/mid-topic"
                },
                "pulsar": {
                  "pulsarConfig": "mesh-test-pulsar"
                },
                "replicas": 1,
                "resources": {
                  "limits": {
                    "cpu": "0.2",
                    "memory": "1.1G"
                  },
                  "requests": {
                    "cpu": "0.1",
                    "memory": "1G"
                  }
                },
                "sinkType": "java.lang.String",
                "sourceType": "java.lang.String"
              },
              {
                "autoAck": true,
                "className": "org.apache.pulsar.functions.api.examples.ExclamationFunction",
                "clusterName": "test-pulsar",
                "forwardSourceMessageProperty": true,
                "input": {
                  "topics": [
                    "persistent://public/default/mid-topic"
                  ]
                },
                "java": {
                  "jar": "pulsar-functions-api-examples.jar",
                  "jarLocation": "public/default/nlu-test-functionmesh-ex2"
                },
                "logTopic": "persistent://public/default/logging-function-logs",
                "maxReplicas": 1,
                "name": "ex2",
                "output": {
                  "topic": "persistent://public/default/functionmesh-output-topic"
                },
                "pulsar": {
                  "pulsarConfig": "mesh-test-pulsar"
                },
                "replicas": 1,
                "resources": {
                  "limits": {
                    "cpu": "0.2",
                    "memory": "1.1G"
                  },
                  "requests": {
                    "cpu": "0.1",
                    "memory": "1G"
                  }
                },
                "sinkType": "java.lang.String",
                "sourceType": "java.lang.String"
              }
            ]
          }
        },
        {
          "apiVersion": "compute.functionmesh.io/v1alpha1",
          "kind": "Sink",
          "metadata": {
            "name": "sink-sample"
          },
          "spec": {
            "autoAck": true,
            "className": "org.apache.pulsar.io.elasticsearch.ElasticSearchSink",
            "clusterName": "test-pulsar",
            "input": {
              "topics": [
                "persistent://public/default/input"
              ]
            },
            "java": {
              "jar": "connectors/pulsar-io-elastic-search-2.7.0-rc-pm-3.nar",
              "jarLocation": ""
            },
            "maxReplicas": 1,
            "pulsar": {
              "pulsarConfig": "test-sink"
            },
            "replicas": 1,
            "resources": {
              "limits": {
                "cpu": "0.2",
                "memory": "1.1G"
              },
              "requests": {
                "cpu": "0.1",
                "memory": "1G"
              }
            },
            "sinkConfig": {
              "elasticSearchUrl": "http://quickstart-es-http.default.svc.cluster.local:9200",
              "indexName": "my_index",
              "password": "wJ757TmoXEd941kXm07Z2GW3",
              "typeName": "doc",
              "username": "elastic"
            },
            "sinkType": "[B",
            "sourceType": "[B"
          }
        },
        {
          "apiVersion": "compute.functionmesh.io/v1alpha1",
          "kind": "Source",
          "metadata": {
            "name": "source-sample"
          },
          "spec": {
            "className": "org.apache.pulsar.io.debezium.mongodb.DebeziumMongoDbSource",
            "clusterName": "test-pulsar",
            "java": {
              "jar": "connectors/pulsar-io-debezium-mongodb-2.7.0-rc-pm-3.nar",
              "jarLocation": ""
            },
            "maxReplicas": 1,
            "output": {
              "producerConf": {
                "maxPendingMessages": 1000,
                "maxPendingMessagesAcrossPartitions": 50000,
                "useThreadLocalProducers": true
              },
              "topic": "persistent://public/default/destination"
            },
            "pulsar": {
              "pulsarConfig": "test-source"
            },
            "replicas": 1,
            "resources": {
              "limits": {
                "cpu": "0.2",
                "memory": "1.1G"
              },
              "requests": {
                "cpu": "0.1",
                "memory": "1G"
              }
            },
            "sinkType": "org.apache.pulsar.common.schema.KeyValue",
            "sourceConfig": {
              "database.whitelist": "inventory",
              "mongodb.hosts": "rs0/mongo-dbz-0.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-1.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-2.mongo.default.svc.cluster.local:27017",
              "mongodb.name": "dbserver1",
              "mongodb.password": "dbz",
              "mongodb.task.id": "1",
              "mongodb.user": "debezium",
              "pulsar.service.url": "pulsar://test-pulsar-broker.default.svc.cluster.local:6650"
            },
            "sourceType": "org.apache.pulsar.common.schema.KeyValue"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.3.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: function-mesh.v0.1.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: FunctionMesh is the Schema for the functionmeshes API
      displayName: Function Mesh
      kind: FunctionMesh
      name: functionmeshes.compute.functionmesh.io
      version: v1alpha1
    - kind: Function
      name: functions.compute.functionmesh.io
      version: v1alpha1
    - description: Topic is the Schema for the sinks API
      displayName: Sink
      kind: Sink
      name: sinks.compute.functionmesh.io
      version: v1alpha1
    - description: Source is the Schema for the sources API
      displayName: Source
      kind: Source
      name: sources.compute.functionmesh.io
      version: v1alpha1
  description: function mesh
  displayName: function-mesh
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - functionmeshes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - functionmeshes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - functions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - functions/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - sinks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - sinks/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - sources
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - compute.functionmesh.io
          resources:
          - sources/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: function-mesh-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: streamnative/function-mesh:v0.1.1
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - pulsar
  - function-mesh
  links:
  - name: Function Mesh
    url: https://function-mesh.domain
  maturity: alpha
  provider:
    name: streamnative
  version: 0.1.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1beta1
    containerPort: 443
    deploymentName: function-mesh-controller-manager
    failurePolicy: Fail
    generateName: vfunction.kb.io
    rules:
    - apiGroups:
      - compute.functionmesh.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - functions
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-compute-functionmesh-io-v1alpha1-function
  - admissionReviewVersions:
    - v1beta1
    containerPort: 443
    deploymentName: function-mesh-controller-manager
    failurePolicy: Fail
    generateName: vsink.kb.io
    rules:
    - apiGroups:
      - compute.functionmesh.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - sinks
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-compute-functionmesh-io-v1alpha1-sink
  - admissionReviewVersions:
    - v1beta1
    containerPort: 443
    deploymentName: function-mesh-controller-manager
    failurePolicy: Fail
    generateName: msink.kb.io
    rules:
    - apiGroups:
      - compute.functionmesh.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - sinks
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-compute-functionmesh-io-v1alpha1-sink
  - admissionReviewVersions:
    - v1beta1
    containerPort: 443
    deploymentName: function-mesh-controller-manager
    failurePolicy: Fail
    generateName: msource.kb.io
    rules:
    - apiGroups:
      - compute.functionmesh.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - sources
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-compute-functionmesh-io-v1alpha1-source
