apiVersion: v1
kind: ConfigMap
metadata:
  name: function-mesh-controller-manager-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "function-mesh-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  config.yaml: |
    {{- if .Values.controllerManager.runnerImages }}
    runnerImages:
{{ toYaml .Values.controllerManager.runnerImages | indent 6 }}
    {{- end }}
    {{- if .Values.controllerManager.runnerImagePullSecrets }}
    runnerImagePullSecrets:
{{ toYaml .Values.controllerManager.runnerImagePullSecrets | indent 6 }}
    {{- end }}
    {{- if .Values.controllerManager.runnerImagePullPolicy }}
    runnerImagePullPolicy:
{{ toYaml .Values.controllerManager.runnerImagePullPolicy | indent 6 }}
    {{- end }}
    {{- if .Values.controllerManager.resourceLabels }}
    resourceLabels:
{{ toYaml .Values.controllerManager.resourceLabels | indent 6 }}
    {{- end }}
    {{- if .Values.controllerManager.resourceAnnotations }}
    resourceAnnotations:
{{ toYaml .Values.controllerManager.resourceAnnotations | indent 6 }}
    {{- end }}
