apiVersion: v1
kind: Service
metadata:
  name: function-mesh-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "function-mesh-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: http-metrics
      port: {{ .Values.controllerManager.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.controllerManager.metrics.port }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager