apiVersion: v1
kind: Service
metadata:
  name: function-mesh-controller-manager-service
  labels:
    app.kubernetes.io/name: {{ template "function-mesh-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager
    helm.sh/chart: { { .Chart.Name } }-{{ .Chart.Version | replace "+"  "_" }}
spec:
  type: {{ .Values.controllerManager.service.type }}
  ports:
  - port: 443
    targetPort: webhook
    protocol: TCP
    name: webhook
  - port: 10080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: { { template "function-mesh-operator.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
    app.kubernetes.io/component: controller-manager
