apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app: function-mesh-operator
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https-metrics-service
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
    app: function-mesh-operator
