# permissions for end users to view functionmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backendconfig-viewer-role
rules:
  - apiGroups:
      - compute.functionmesh.io
    resources:
      - backendconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - compute.functionmesh.io
    resources:
      - backendconfigs/status
    verbs:
      - get
