# permissions for end users to edit functionmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backendconfig-editor-role
rules:
  - apiGroups:
      - compute.functionmesh.io
    resources:
      - backendconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - compute.functionmesh.io
    resources:
      - backendconfigs/status
    verbs:
      - get
