/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.function;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * V1alpha1FunctionSpecInputSourceSpecs
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T11:47:27.069Z[Etc/UTC]")
public class V1alpha1FunctionSpecInputSourceSpecs {
  public static final String SERIALIZED_NAME_CONSUMER_PROPERTIES = "consumerProperties";
  @SerializedName(SERIALIZED_NAME_CONSUMER_PROPERTIES)
  private Map<String, String> consumerProperties = null;

  public static final String SERIALIZED_NAME_CRYPTO_CONFIG = "cryptoConfig";
  @SerializedName(SERIALIZED_NAME_CRYPTO_CONFIG)
  private V1alpha1FunctionSpecInputCryptoConfig cryptoConfig;

  public static final String SERIALIZED_NAME_IS_REGEX_PATTERN = "isRegexPattern";
  @SerializedName(SERIALIZED_NAME_IS_REGEX_PATTERN)
  private Boolean isRegexPattern;

  public static final String SERIALIZED_NAME_RECEIVER_QUEUE_SIZE = "receiverQueueSize";
  @SerializedName(SERIALIZED_NAME_RECEIVER_QUEUE_SIZE)
  private Integer receiverQueueSize;

  public static final String SERIALIZED_NAME_SCHEMA_PROPERTIES = "schemaProperties";
  @SerializedName(SERIALIZED_NAME_SCHEMA_PROPERTIES)
  private Map<String, String> schemaProperties = null;

  public static final String SERIALIZED_NAME_SCHEMA_TYPE = "schemaType";
  @SerializedName(SERIALIZED_NAME_SCHEMA_TYPE)
  private String schemaType;

  public static final String SERIALIZED_NAME_SERDE_CLASSNAME = "serdeClassname";
  @SerializedName(SERIALIZED_NAME_SERDE_CLASSNAME)
  private String serdeClassname;


  public V1alpha1FunctionSpecInputSourceSpecs consumerProperties(Map<String, String> consumerProperties) {
    
    this.consumerProperties = consumerProperties;
    return this;
  }

  public V1alpha1FunctionSpecInputSourceSpecs putConsumerPropertiesItem(String key, String consumerPropertiesItem) {
    if (this.consumerProperties == null) {
      this.consumerProperties = new HashMap<String, String>();
    }
    this.consumerProperties.put(key, consumerPropertiesItem);
    return this;
  }

   /**
   * Get consumerProperties
   * @return consumerProperties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getConsumerProperties() {
    return consumerProperties;
  }


  public void setConsumerProperties(Map<String, String> consumerProperties) {
    this.consumerProperties = consumerProperties;
  }


  public V1alpha1FunctionSpecInputSourceSpecs cryptoConfig(V1alpha1FunctionSpecInputCryptoConfig cryptoConfig) {
    
    this.cryptoConfig = cryptoConfig;
    return this;
  }

   /**
   * Get cryptoConfig
   * @return cryptoConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecInputCryptoConfig getCryptoConfig() {
    return cryptoConfig;
  }


  public void setCryptoConfig(V1alpha1FunctionSpecInputCryptoConfig cryptoConfig) {
    this.cryptoConfig = cryptoConfig;
  }


  public V1alpha1FunctionSpecInputSourceSpecs isRegexPattern(Boolean isRegexPattern) {
    
    this.isRegexPattern = isRegexPattern;
    return this;
  }

   /**
   * Get isRegexPattern
   * @return isRegexPattern
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsRegexPattern() {
    return isRegexPattern;
  }


  public void setIsRegexPattern(Boolean isRegexPattern) {
    this.isRegexPattern = isRegexPattern;
  }


  public V1alpha1FunctionSpecInputSourceSpecs receiverQueueSize(Integer receiverQueueSize) {
    
    this.receiverQueueSize = receiverQueueSize;
    return this;
  }

   /**
   * Get receiverQueueSize
   * @return receiverQueueSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReceiverQueueSize() {
    return receiverQueueSize;
  }


  public void setReceiverQueueSize(Integer receiverQueueSize) {
    this.receiverQueueSize = receiverQueueSize;
  }


  public V1alpha1FunctionSpecInputSourceSpecs schemaProperties(Map<String, String> schemaProperties) {
    
    this.schemaProperties = schemaProperties;
    return this;
  }

  public V1alpha1FunctionSpecInputSourceSpecs putSchemaPropertiesItem(String key, String schemaPropertiesItem) {
    if (this.schemaProperties == null) {
      this.schemaProperties = new HashMap<String, String>();
    }
    this.schemaProperties.put(key, schemaPropertiesItem);
    return this;
  }

   /**
   * Get schemaProperties
   * @return schemaProperties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getSchemaProperties() {
    return schemaProperties;
  }


  public void setSchemaProperties(Map<String, String> schemaProperties) {
    this.schemaProperties = schemaProperties;
  }


  public V1alpha1FunctionSpecInputSourceSpecs schemaType(String schemaType) {
    
    this.schemaType = schemaType;
    return this;
  }

   /**
   * Get schemaType
   * @return schemaType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSchemaType() {
    return schemaType;
  }


  public void setSchemaType(String schemaType) {
    this.schemaType = schemaType;
  }


  public V1alpha1FunctionSpecInputSourceSpecs serdeClassname(String serdeClassname) {
    
    this.serdeClassname = serdeClassname;
    return this;
  }

   /**
   * Get serdeClassname
   * @return serdeClassname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSerdeClassname() {
    return serdeClassname;
  }


  public void setSerdeClassname(String serdeClassname) {
    this.serdeClassname = serdeClassname;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionSpecInputSourceSpecs v1alpha1FunctionSpecInputSourceSpecs = (V1alpha1FunctionSpecInputSourceSpecs) o;
    return Objects.equals(this.consumerProperties, v1alpha1FunctionSpecInputSourceSpecs.consumerProperties) &&
        Objects.equals(this.cryptoConfig, v1alpha1FunctionSpecInputSourceSpecs.cryptoConfig) &&
        Objects.equals(this.isRegexPattern, v1alpha1FunctionSpecInputSourceSpecs.isRegexPattern) &&
        Objects.equals(this.receiverQueueSize, v1alpha1FunctionSpecInputSourceSpecs.receiverQueueSize) &&
        Objects.equals(this.schemaProperties, v1alpha1FunctionSpecInputSourceSpecs.schemaProperties) &&
        Objects.equals(this.schemaType, v1alpha1FunctionSpecInputSourceSpecs.schemaType) &&
        Objects.equals(this.serdeClassname, v1alpha1FunctionSpecInputSourceSpecs.serdeClassname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumerProperties, cryptoConfig, isRegexPattern, receiverQueueSize, schemaProperties, schemaType, serdeClassname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionSpecInputSourceSpecs {\n");
    sb.append("    consumerProperties: ").append(toIndentedString(consumerProperties)).append("\n");
    sb.append("    cryptoConfig: ").append(toIndentedString(cryptoConfig)).append("\n");
    sb.append("    isRegexPattern: ").append(toIndentedString(isRegexPattern)).append("\n");
    sb.append("    receiverQueueSize: ").append(toIndentedString(receiverQueueSize)).append("\n");
    sb.append("    schemaProperties: ").append(toIndentedString(schemaProperties)).append("\n");
    sb.append("    schemaType: ").append(toIndentedString(schemaType)).append("\n");
    sb.append("    serdeClassname: ").append(toIndentedString(serdeClassname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

