/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.function;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * V1alpha1FunctionSpecOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T11:47:27.069Z[Etc/UTC]")
public class V1alpha1FunctionSpecOutput {
  public static final String SERIALIZED_NAME_CUSTOM_SCHEMA_SINKS = "customSchemaSinks";
  @SerializedName(SERIALIZED_NAME_CUSTOM_SCHEMA_SINKS)
  private Map<String, String> customSchemaSinks = null;

  public static final String SERIALIZED_NAME_PRODUCER_CONF = "producerConf";
  @SerializedName(SERIALIZED_NAME_PRODUCER_CONF)
  private V1alpha1FunctionSpecOutputProducerConf producerConf;

  public static final String SERIALIZED_NAME_SINK_SCHEMA_TYPE = "sinkSchemaType";
  @SerializedName(SERIALIZED_NAME_SINK_SCHEMA_TYPE)
  private String sinkSchemaType;

  public static final String SERIALIZED_NAME_SINK_SERDE_CLASS_NAME = "sinkSerdeClassName";
  @SerializedName(SERIALIZED_NAME_SINK_SERDE_CLASS_NAME)
  private String sinkSerdeClassName;

  public static final String SERIALIZED_NAME_TOPIC = "topic";
  @SerializedName(SERIALIZED_NAME_TOPIC)
  private String topic;


  public V1alpha1FunctionSpecOutput customSchemaSinks(Map<String, String> customSchemaSinks) {
    
    this.customSchemaSinks = customSchemaSinks;
    return this;
  }

  public V1alpha1FunctionSpecOutput putCustomSchemaSinksItem(String key, String customSchemaSinksItem) {
    if (this.customSchemaSinks == null) {
      this.customSchemaSinks = new HashMap<String, String>();
    }
    this.customSchemaSinks.put(key, customSchemaSinksItem);
    return this;
  }

   /**
   * Get customSchemaSinks
   * @return customSchemaSinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getCustomSchemaSinks() {
    return customSchemaSinks;
  }


  public void setCustomSchemaSinks(Map<String, String> customSchemaSinks) {
    this.customSchemaSinks = customSchemaSinks;
  }


  public V1alpha1FunctionSpecOutput producerConf(V1alpha1FunctionSpecOutputProducerConf producerConf) {
    
    this.producerConf = producerConf;
    return this;
  }

   /**
   * Get producerConf
   * @return producerConf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecOutputProducerConf getProducerConf() {
    return producerConf;
  }


  public void setProducerConf(V1alpha1FunctionSpecOutputProducerConf producerConf) {
    this.producerConf = producerConf;
  }


  public V1alpha1FunctionSpecOutput sinkSchemaType(String sinkSchemaType) {
    
    this.sinkSchemaType = sinkSchemaType;
    return this;
  }

   /**
   * Get sinkSchemaType
   * @return sinkSchemaType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSinkSchemaType() {
    return sinkSchemaType;
  }


  public void setSinkSchemaType(String sinkSchemaType) {
    this.sinkSchemaType = sinkSchemaType;
  }


  public V1alpha1FunctionSpecOutput sinkSerdeClassName(String sinkSerdeClassName) {
    
    this.sinkSerdeClassName = sinkSerdeClassName;
    return this;
  }

   /**
   * Get sinkSerdeClassName
   * @return sinkSerdeClassName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSinkSerdeClassName() {
    return sinkSerdeClassName;
  }


  public void setSinkSerdeClassName(String sinkSerdeClassName) {
    this.sinkSerdeClassName = sinkSerdeClassName;
  }


  public V1alpha1FunctionSpecOutput topic(String topic) {
    
    this.topic = topic;
    return this;
  }

   /**
   * Get topic
   * @return topic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTopic() {
    return topic;
  }


  public void setTopic(String topic) {
    this.topic = topic;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionSpecOutput v1alpha1FunctionSpecOutput = (V1alpha1FunctionSpecOutput) o;
    return Objects.equals(this.customSchemaSinks, v1alpha1FunctionSpecOutput.customSchemaSinks) &&
        Objects.equals(this.producerConf, v1alpha1FunctionSpecOutput.producerConf) &&
        Objects.equals(this.sinkSchemaType, v1alpha1FunctionSpecOutput.sinkSchemaType) &&
        Objects.equals(this.sinkSerdeClassName, v1alpha1FunctionSpecOutput.sinkSerdeClassName) &&
        Objects.equals(this.topic, v1alpha1FunctionSpecOutput.topic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customSchemaSinks, producerConf, sinkSchemaType, sinkSerdeClassName, topic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionSpecOutput {\n");
    sb.append("    customSchemaSinks: ").append(toIndentedString(customSchemaSinks)).append("\n");
    sb.append("    producerConf: ").append(toIndentedString(producerConf)).append("\n");
    sb.append("    sinkSchemaType: ").append(toIndentedString(sinkSchemaType)).append("\n");
    sb.append("    sinkSerdeClassName: ").append(toIndentedString(sinkSerdeClassName)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

