/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.function;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * FunctionSpec defines the desired state of Function
 */
@ApiModel(description = "FunctionSpec defines the desired state of Function")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-19T11:47:27.069Z[Etc/UTC]")
public class V1alpha1FunctionSpec {
  public static final String SERIALIZED_NAME_AUTO_ACK = "autoAck";
  @SerializedName(SERIALIZED_NAME_AUTO_ACK)
  private Boolean autoAck;

  public static final String SERIALIZED_NAME_CLASS_NAME = "className";
  @SerializedName(SERIALIZED_NAME_CLASS_NAME)
  private String className;

  public static final String SERIALIZED_NAME_CLEANUP_SUBSCRIPTION = "cleanupSubscription";
  @SerializedName(SERIALIZED_NAME_CLEANUP_SUBSCRIPTION)
  private Boolean cleanupSubscription;

  public static final String SERIALIZED_NAME_CLUSTER_NAME = "clusterName";
  @SerializedName(SERIALIZED_NAME_CLUSTER_NAME)
  private String clusterName;

  public static final String SERIALIZED_NAME_DEAD_LETTER_TOPIC = "deadLetterTopic";
  @SerializedName(SERIALIZED_NAME_DEAD_LETTER_TOPIC)
  private String deadLetterTopic;

  public static final String SERIALIZED_NAME_FORWARD_SOURCE_MESSAGE_PROPERTY = "forwardSourceMessageProperty";
  @SerializedName(SERIALIZED_NAME_FORWARD_SOURCE_MESSAGE_PROPERTY)
  private Boolean forwardSourceMessageProperty;

  public static final String SERIALIZED_NAME_FUNC_CONFIG = "funcConfig";
  @SerializedName(SERIALIZED_NAME_FUNC_CONFIG)
  private Map<String, String> funcConfig = null;

  public static final String SERIALIZED_NAME_GOLANG = "golang";
  @SerializedName(SERIALIZED_NAME_GOLANG)
  private V1alpha1FunctionSpecGolang golang;

  public static final String SERIALIZED_NAME_INPUT = "input";
  @SerializedName(SERIALIZED_NAME_INPUT)
  private V1alpha1FunctionSpecInput input;

  public static final String SERIALIZED_NAME_JAVA = "java";
  @SerializedName(SERIALIZED_NAME_JAVA)
  private V1alpha1FunctionSpecJava java;

  public static final String SERIALIZED_NAME_LOG_TOPIC = "logTopic";
  @SerializedName(SERIALIZED_NAME_LOG_TOPIC)
  private String logTopic;

  public static final String SERIALIZED_NAME_MAX_MESSAGE_RETRY = "maxMessageRetry";
  @SerializedName(SERIALIZED_NAME_MAX_MESSAGE_RETRY)
  private Integer maxMessageRetry;

  public static final String SERIALIZED_NAME_MAX_PENDING_ASYNC_REQUESTS = "maxPendingAsyncRequests";
  @SerializedName(SERIALIZED_NAME_MAX_PENDING_ASYNC_REQUESTS)
  private Integer maxPendingAsyncRequests;

  public static final String SERIALIZED_NAME_MAX_REPLICAS = "maxReplicas";
  @SerializedName(SERIALIZED_NAME_MAX_REPLICAS)
  private Integer maxReplicas;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OUTPUT = "output";
  @SerializedName(SERIALIZED_NAME_OUTPUT)
  private V1alpha1FunctionSpecOutput output;

  public static final String SERIALIZED_NAME_POD = "pod";
  @SerializedName(SERIALIZED_NAME_POD)
  private V1alpha1FunctionSpecPod pod;

  public static final String SERIALIZED_NAME_PROCESSING_GUARANTEE = "processingGuarantee";
  @SerializedName(SERIALIZED_NAME_PROCESSING_GUARANTEE)
  private String processingGuarantee;

  public static final String SERIALIZED_NAME_PULSAR = "pulsar";
  @SerializedName(SERIALIZED_NAME_PULSAR)
  private V1alpha1FunctionSpecPulsar pulsar;

  public static final String SERIALIZED_NAME_PYTHON = "python";
  @SerializedName(SERIALIZED_NAME_PYTHON)
  private V1alpha1FunctionSpecPython python;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_RESOURCES = "resources";
  @SerializedName(SERIALIZED_NAME_RESOURCES)
  private V1alpha1FunctionSpecResources resources;

  public static final String SERIALIZED_NAME_RETAIN_KEY_ORDERING = "retainKeyOrdering";
  @SerializedName(SERIALIZED_NAME_RETAIN_KEY_ORDERING)
  private Boolean retainKeyOrdering;

  public static final String SERIALIZED_NAME_RETAIN_ORDERING = "retainOrdering";
  @SerializedName(SERIALIZED_NAME_RETAIN_ORDERING)
  private Boolean retainOrdering;

  public static final String SERIALIZED_NAME_RUNTIME_FLAGS = "runtimeFlags";
  @SerializedName(SERIALIZED_NAME_RUNTIME_FLAGS)
  private String runtimeFlags;

  public static final String SERIALIZED_NAME_SECRETS_MAP = "secretsMap";
  @SerializedName(SERIALIZED_NAME_SECRETS_MAP)
  private Map<String, V1alpha1FunctionSpecSecretsMap> secretsMap = null;

  public static final String SERIALIZED_NAME_SINK_TYPE = "sinkType";
  @SerializedName(SERIALIZED_NAME_SINK_TYPE)
  private String sinkType;

  public static final String SERIALIZED_NAME_SOURCE_TYPE = "sourceType";
  @SerializedName(SERIALIZED_NAME_SOURCE_TYPE)
  private String sourceType;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_NAME = "subscriptionName";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_NAME)
  private String subscriptionName;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_POSITION = "subscriptionPosition";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_POSITION)
  private String subscriptionPosition;

  public static final String SERIALIZED_NAME_TENANT = "tenant";
  @SerializedName(SERIALIZED_NAME_TENANT)
  private String tenant;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private Integer timeout;


  public V1alpha1FunctionSpec autoAck(Boolean autoAck) {
    
    this.autoAck = autoAck;
    return this;
  }

   /**
   * Get autoAck
   * @return autoAck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAutoAck() {
    return autoAck;
  }


  public void setAutoAck(Boolean autoAck) {
    this.autoAck = autoAck;
  }


  public V1alpha1FunctionSpec className(String className) {
    
    this.className = className;
    return this;
  }

   /**
   * Get className
   * @return className
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClassName() {
    return className;
  }


  public void setClassName(String className) {
    this.className = className;
  }


  public V1alpha1FunctionSpec cleanupSubscription(Boolean cleanupSubscription) {
    
    this.cleanupSubscription = cleanupSubscription;
    return this;
  }

   /**
   * Get cleanupSubscription
   * @return cleanupSubscription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCleanupSubscription() {
    return cleanupSubscription;
  }


  public void setCleanupSubscription(Boolean cleanupSubscription) {
    this.cleanupSubscription = cleanupSubscription;
  }


  public V1alpha1FunctionSpec clusterName(String clusterName) {
    
    this.clusterName = clusterName;
    return this;
  }

   /**
   * Get clusterName
   * @return clusterName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClusterName() {
    return clusterName;
  }


  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }


  public V1alpha1FunctionSpec deadLetterTopic(String deadLetterTopic) {
    
    this.deadLetterTopic = deadLetterTopic;
    return this;
  }

   /**
   * Get deadLetterTopic
   * @return deadLetterTopic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDeadLetterTopic() {
    return deadLetterTopic;
  }


  public void setDeadLetterTopic(String deadLetterTopic) {
    this.deadLetterTopic = deadLetterTopic;
  }


  public V1alpha1FunctionSpec forwardSourceMessageProperty(Boolean forwardSourceMessageProperty) {
    
    this.forwardSourceMessageProperty = forwardSourceMessageProperty;
    return this;
  }

   /**
   * Get forwardSourceMessageProperty
   * @return forwardSourceMessageProperty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getForwardSourceMessageProperty() {
    return forwardSourceMessageProperty;
  }


  public void setForwardSourceMessageProperty(Boolean forwardSourceMessageProperty) {
    this.forwardSourceMessageProperty = forwardSourceMessageProperty;
  }


  public V1alpha1FunctionSpec funcConfig(Map<String, String> funcConfig) {
    
    this.funcConfig = funcConfig;
    return this;
  }

  public V1alpha1FunctionSpec putFuncConfigItem(String key, String funcConfigItem) {
    if (this.funcConfig == null) {
      this.funcConfig = new HashMap<String, String>();
    }
    this.funcConfig.put(key, funcConfigItem);
    return this;
  }

   /**
   * Get funcConfig
   * @return funcConfig
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getFuncConfig() {
    return funcConfig;
  }


  public void setFuncConfig(Map<String, String> funcConfig) {
    this.funcConfig = funcConfig;
  }


  public V1alpha1FunctionSpec golang(V1alpha1FunctionSpecGolang golang) {
    
    this.golang = golang;
    return this;
  }

   /**
   * Get golang
   * @return golang
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecGolang getGolang() {
    return golang;
  }


  public void setGolang(V1alpha1FunctionSpecGolang golang) {
    this.golang = golang;
  }


  public V1alpha1FunctionSpec input(V1alpha1FunctionSpecInput input) {
    
    this.input = input;
    return this;
  }

   /**
   * Get input
   * @return input
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecInput getInput() {
    return input;
  }


  public void setInput(V1alpha1FunctionSpecInput input) {
    this.input = input;
  }


  public V1alpha1FunctionSpec java(V1alpha1FunctionSpecJava java) {
    
    this.java = java;
    return this;
  }

   /**
   * Get java
   * @return java
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecJava getJava() {
    return java;
  }


  public void setJava(V1alpha1FunctionSpecJava java) {
    this.java = java;
  }


  public V1alpha1FunctionSpec logTopic(String logTopic) {
    
    this.logTopic = logTopic;
    return this;
  }

   /**
   * Get logTopic
   * @return logTopic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLogTopic() {
    return logTopic;
  }


  public void setLogTopic(String logTopic) {
    this.logTopic = logTopic;
  }


  public V1alpha1FunctionSpec maxMessageRetry(Integer maxMessageRetry) {
    
    this.maxMessageRetry = maxMessageRetry;
    return this;
  }

   /**
   * Get maxMessageRetry
   * @return maxMessageRetry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxMessageRetry() {
    return maxMessageRetry;
  }


  public void setMaxMessageRetry(Integer maxMessageRetry) {
    this.maxMessageRetry = maxMessageRetry;
  }


  public V1alpha1FunctionSpec maxPendingAsyncRequests(Integer maxPendingAsyncRequests) {
    
    this.maxPendingAsyncRequests = maxPendingAsyncRequests;
    return this;
  }

   /**
   * Get maxPendingAsyncRequests
   * @return maxPendingAsyncRequests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxPendingAsyncRequests() {
    return maxPendingAsyncRequests;
  }


  public void setMaxPendingAsyncRequests(Integer maxPendingAsyncRequests) {
    this.maxPendingAsyncRequests = maxPendingAsyncRequests;
  }


  public V1alpha1FunctionSpec maxReplicas(Integer maxReplicas) {
    
    this.maxReplicas = maxReplicas;
    return this;
  }

   /**
   * Get maxReplicas
   * @return maxReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxReplicas() {
    return maxReplicas;
  }


  public void setMaxReplicas(Integer maxReplicas) {
    this.maxReplicas = maxReplicas;
  }


  public V1alpha1FunctionSpec name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \&quot;make\&quot; to regenerate code after modifying this file
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"make\" to regenerate code after modifying this file")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1FunctionSpec output(V1alpha1FunctionSpecOutput output) {
    
    this.output = output;
    return this;
  }

   /**
   * Get output
   * @return output
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecOutput getOutput() {
    return output;
  }


  public void setOutput(V1alpha1FunctionSpecOutput output) {
    this.output = output;
  }


  public V1alpha1FunctionSpec pod(V1alpha1FunctionSpecPod pod) {
    
    this.pod = pod;
    return this;
  }

   /**
   * Get pod
   * @return pod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecPod getPod() {
    return pod;
  }


  public void setPod(V1alpha1FunctionSpecPod pod) {
    this.pod = pod;
  }


  public V1alpha1FunctionSpec processingGuarantee(String processingGuarantee) {
    
    this.processingGuarantee = processingGuarantee;
    return this;
  }

   /**
   * Get processingGuarantee
   * @return processingGuarantee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProcessingGuarantee() {
    return processingGuarantee;
  }


  public void setProcessingGuarantee(String processingGuarantee) {
    this.processingGuarantee = processingGuarantee;
  }


  public V1alpha1FunctionSpec pulsar(V1alpha1FunctionSpecPulsar pulsar) {
    
    this.pulsar = pulsar;
    return this;
  }

   /**
   * Get pulsar
   * @return pulsar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecPulsar getPulsar() {
    return pulsar;
  }


  public void setPulsar(V1alpha1FunctionSpecPulsar pulsar) {
    this.pulsar = pulsar;
  }


  public V1alpha1FunctionSpec python(V1alpha1FunctionSpecPython python) {
    
    this.python = python;
    return this;
  }

   /**
   * Get python
   * @return python
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecPython getPython() {
    return python;
  }


  public void setPython(V1alpha1FunctionSpecPython python) {
    this.python = python;
  }


  public V1alpha1FunctionSpec replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Get replicas
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1alpha1FunctionSpec resources(V1alpha1FunctionSpecResources resources) {
    
    this.resources = resources;
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1FunctionSpecResources getResources() {
    return resources;
  }


  public void setResources(V1alpha1FunctionSpecResources resources) {
    this.resources = resources;
  }


  public V1alpha1FunctionSpec retainKeyOrdering(Boolean retainKeyOrdering) {
    
    this.retainKeyOrdering = retainKeyOrdering;
    return this;
  }

   /**
   * Get retainKeyOrdering
   * @return retainKeyOrdering
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRetainKeyOrdering() {
    return retainKeyOrdering;
  }


  public void setRetainKeyOrdering(Boolean retainKeyOrdering) {
    this.retainKeyOrdering = retainKeyOrdering;
  }


  public V1alpha1FunctionSpec retainOrdering(Boolean retainOrdering) {
    
    this.retainOrdering = retainOrdering;
    return this;
  }

   /**
   * Get retainOrdering
   * @return retainOrdering
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRetainOrdering() {
    return retainOrdering;
  }


  public void setRetainOrdering(Boolean retainOrdering) {
    this.retainOrdering = retainOrdering;
  }


  public V1alpha1FunctionSpec runtimeFlags(String runtimeFlags) {
    
    this.runtimeFlags = runtimeFlags;
    return this;
  }

   /**
   * Get runtimeFlags
   * @return runtimeFlags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRuntimeFlags() {
    return runtimeFlags;
  }


  public void setRuntimeFlags(String runtimeFlags) {
    this.runtimeFlags = runtimeFlags;
  }


  public V1alpha1FunctionSpec secretsMap(Map<String, V1alpha1FunctionSpecSecretsMap> secretsMap) {
    
    this.secretsMap = secretsMap;
    return this;
  }

  public V1alpha1FunctionSpec putSecretsMapItem(String key, V1alpha1FunctionSpecSecretsMap secretsMapItem) {
    if (this.secretsMap == null) {
      this.secretsMap = new HashMap<String, V1alpha1FunctionSpecSecretsMap>();
    }
    this.secretsMap.put(key, secretsMapItem);
    return this;
  }

   /**
   * Get secretsMap
   * @return secretsMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, V1alpha1FunctionSpecSecretsMap> getSecretsMap() {
    return secretsMap;
  }


  public void setSecretsMap(Map<String, V1alpha1FunctionSpecSecretsMap> secretsMap) {
    this.secretsMap = secretsMap;
  }


  public V1alpha1FunctionSpec sinkType(String sinkType) {
    
    this.sinkType = sinkType;
    return this;
  }

   /**
   * Get sinkType
   * @return sinkType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSinkType() {
    return sinkType;
  }


  public void setSinkType(String sinkType) {
    this.sinkType = sinkType;
  }


  public V1alpha1FunctionSpec sourceType(String sourceType) {
    
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Get sourceType
   * @return sourceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSourceType() {
    return sourceType;
  }


  public void setSourceType(String sourceType) {
    this.sourceType = sourceType;
  }


  public V1alpha1FunctionSpec subscriptionName(String subscriptionName) {
    
    this.subscriptionName = subscriptionName;
    return this;
  }

   /**
   * Get subscriptionName
   * @return subscriptionName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionName() {
    return subscriptionName;
  }


  public void setSubscriptionName(String subscriptionName) {
    this.subscriptionName = subscriptionName;
  }


  public V1alpha1FunctionSpec subscriptionPosition(String subscriptionPosition) {
    
    this.subscriptionPosition = subscriptionPosition;
    return this;
  }

   /**
   * Get subscriptionPosition
   * @return subscriptionPosition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionPosition() {
    return subscriptionPosition;
  }


  public void setSubscriptionPosition(String subscriptionPosition) {
    this.subscriptionPosition = subscriptionPosition;
  }


  public V1alpha1FunctionSpec tenant(String tenant) {
    
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTenant() {
    return tenant;
  }


  public void setTenant(String tenant) {
    this.tenant = tenant;
  }


  public V1alpha1FunctionSpec timeout(Integer timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * Get timeout
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTimeout() {
    return timeout;
  }


  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1FunctionSpec v1alpha1FunctionSpec = (V1alpha1FunctionSpec) o;
    return Objects.equals(this.autoAck, v1alpha1FunctionSpec.autoAck) &&
        Objects.equals(this.className, v1alpha1FunctionSpec.className) &&
        Objects.equals(this.cleanupSubscription, v1alpha1FunctionSpec.cleanupSubscription) &&
        Objects.equals(this.clusterName, v1alpha1FunctionSpec.clusterName) &&
        Objects.equals(this.deadLetterTopic, v1alpha1FunctionSpec.deadLetterTopic) &&
        Objects.equals(this.forwardSourceMessageProperty, v1alpha1FunctionSpec.forwardSourceMessageProperty) &&
        Objects.equals(this.funcConfig, v1alpha1FunctionSpec.funcConfig) &&
        Objects.equals(this.golang, v1alpha1FunctionSpec.golang) &&
        Objects.equals(this.input, v1alpha1FunctionSpec.input) &&
        Objects.equals(this.java, v1alpha1FunctionSpec.java) &&
        Objects.equals(this.logTopic, v1alpha1FunctionSpec.logTopic) &&
        Objects.equals(this.maxMessageRetry, v1alpha1FunctionSpec.maxMessageRetry) &&
        Objects.equals(this.maxPendingAsyncRequests, v1alpha1FunctionSpec.maxPendingAsyncRequests) &&
        Objects.equals(this.maxReplicas, v1alpha1FunctionSpec.maxReplicas) &&
        Objects.equals(this.name, v1alpha1FunctionSpec.name) &&
        Objects.equals(this.output, v1alpha1FunctionSpec.output) &&
        Objects.equals(this.pod, v1alpha1FunctionSpec.pod) &&
        Objects.equals(this.processingGuarantee, v1alpha1FunctionSpec.processingGuarantee) &&
        Objects.equals(this.pulsar, v1alpha1FunctionSpec.pulsar) &&
        Objects.equals(this.python, v1alpha1FunctionSpec.python) &&
        Objects.equals(this.replicas, v1alpha1FunctionSpec.replicas) &&
        Objects.equals(this.resources, v1alpha1FunctionSpec.resources) &&
        Objects.equals(this.retainKeyOrdering, v1alpha1FunctionSpec.retainKeyOrdering) &&
        Objects.equals(this.retainOrdering, v1alpha1FunctionSpec.retainOrdering) &&
        Objects.equals(this.runtimeFlags, v1alpha1FunctionSpec.runtimeFlags) &&
        Objects.equals(this.secretsMap, v1alpha1FunctionSpec.secretsMap) &&
        Objects.equals(this.sinkType, v1alpha1FunctionSpec.sinkType) &&
        Objects.equals(this.sourceType, v1alpha1FunctionSpec.sourceType) &&
        Objects.equals(this.subscriptionName, v1alpha1FunctionSpec.subscriptionName) &&
        Objects.equals(this.subscriptionPosition, v1alpha1FunctionSpec.subscriptionPosition) &&
        Objects.equals(this.tenant, v1alpha1FunctionSpec.tenant) &&
        Objects.equals(this.timeout, v1alpha1FunctionSpec.timeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoAck, className, cleanupSubscription, clusterName, deadLetterTopic, forwardSourceMessageProperty, funcConfig, golang, input, java, logTopic, maxMessageRetry, maxPendingAsyncRequests, maxReplicas, name, output, pod, processingGuarantee, pulsar, python, replicas, resources, retainKeyOrdering, retainOrdering, runtimeFlags, secretsMap, sinkType, sourceType, subscriptionName, subscriptionPosition, tenant, timeout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1FunctionSpec {\n");
    sb.append("    autoAck: ").append(toIndentedString(autoAck)).append("\n");
    sb.append("    className: ").append(toIndentedString(className)).append("\n");
    sb.append("    cleanupSubscription: ").append(toIndentedString(cleanupSubscription)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    deadLetterTopic: ").append(toIndentedString(deadLetterTopic)).append("\n");
    sb.append("    forwardSourceMessageProperty: ").append(toIndentedString(forwardSourceMessageProperty)).append("\n");
    sb.append("    funcConfig: ").append(toIndentedString(funcConfig)).append("\n");
    sb.append("    golang: ").append(toIndentedString(golang)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    java: ").append(toIndentedString(java)).append("\n");
    sb.append("    logTopic: ").append(toIndentedString(logTopic)).append("\n");
    sb.append("    maxMessageRetry: ").append(toIndentedString(maxMessageRetry)).append("\n");
    sb.append("    maxPendingAsyncRequests: ").append(toIndentedString(maxPendingAsyncRequests)).append("\n");
    sb.append("    maxReplicas: ").append(toIndentedString(maxReplicas)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    pod: ").append(toIndentedString(pod)).append("\n");
    sb.append("    processingGuarantee: ").append(toIndentedString(processingGuarantee)).append("\n");
    sb.append("    pulsar: ").append(toIndentedString(pulsar)).append("\n");
    sb.append("    python: ").append(toIndentedString(python)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    retainKeyOrdering: ").append(toIndentedString(retainKeyOrdering)).append("\n");
    sb.append("    retainOrdering: ").append(toIndentedString(retainOrdering)).append("\n");
    sb.append("    runtimeFlags: ").append(toIndentedString(runtimeFlags)).append("\n");
    sb.append("    secretsMap: ").append(toIndentedString(secretsMap)).append("\n");
    sb.append("    sinkType: ").append(toIndentedString(sinkType)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    subscriptionName: ").append(toIndentedString(subscriptionName)).append("\n");
    sb.append("    subscriptionPosition: ").append(toIndentedString(subscriptionPosition)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

