apiVersion: compute.functionmesh.io/v1alpha1
kind: ConnectorCatalog
metadata:
  labels:
    app.kubernetes.io/name: connectorcatalog
    app.kubernetes.io/instance: connectorcatalog-sample
    app.kubernetes.io/part-of: function-mesh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: function-mesh
  name: connectorcatalog-sample
spec:
  connectorDefinitions:
    - id: pulsar-io-data-generator
      name: data-generator
      description: Test data generator connector
      sourceClass: org.apache.pulsar.io.datagenerator.DataGeneratorSource
      sourceConfigClass: org.apache.pulsar.io.datagenerator.DataGeneratorSourceConfig
      sinkClass: org.apache.pulsar.io.datagenerator.DataGeneratorPrintSink
      imageRepository: streamnative/pulsar-io-data-generator
      version: 2.9.2.17
      imageTag: 2.9.2.17
      typeClassName: org.apache.pulsar.io.datagenerator.Person
      sourceConfigFieldDefinitions:
        - fieldName: sleepBetweenMessages
          typeName: long
          attributes:
              help: "How long to sleep between emitting messages"
              defaultValue: "50"
              sensitive: "false"
              required: "true"
    - id: pulsar-io-kafka
      name: kafka
      description: Kafka Source
      sourceClass: org.apache.pulsar.io.kafka.KafkaBytesSource
      imageRepository: streamnative/pulsar-io-kafka
      version: 2.9.2.17
      imageTag: 2.9.2.17
      sourceConfigClass: org.apache.pulsar.io.kafka.KafkaSourceConfig
      sourceTypeClassName: java.nio.ByteBuffer
    - id: pulsar-io-cloud-storage
      name: cloud-storage
      description: Cloud storage Sink
      sinkClass: org.apache.pulsar.io.jcloud.sink.CloudStorageGenericRecordSink
      sinkConfigClass: org.apache.pulsar.io.jcloud.sink.CloudStorageSinkConfig
      imageRepository: streamnative/pulsar-io-cloud-storage
      version: 2.9.2.17
      imageTag: 2.9.2.17
      typeClassName: org.apache.pulsar.client.api.schema.GenericRecord
