apiVersion: compute.functionmesh.io/v1alpha1
kind: ConnectorCatalog
metadata:
  labels:
    app.kubernetes.io/name: connectorcatalog
    app.kubernetes.io/instance: connectorcatalog-sample
    app.kubernetes.io/part-of: function-mesh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: function-mesh
  name: connectorcatalog-sample
spec:
  # TODO(user): Add fields here
