//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigFieldDefinition) DeepCopyInto(out *ConfigFieldDefinition) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigFieldDefinition.
func (in *ConfigFieldDefinition) DeepCopy() *ConfigFieldDefinition {
	if in == nil {
		return nil
	}
	out := new(ConfigFieldDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCatalog) DeepCopyInto(out *ConnectorCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCatalog.
func (in *ConnectorCatalog) DeepCopy() *ConnectorCatalog {
	if in == nil {
		return nil
	}
	out := new(ConnectorCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCatalogList) DeepCopyInto(out *ConnectorCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectorCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCatalogList.
func (in *ConnectorCatalogList) DeepCopy() *ConnectorCatalogList {
	if in == nil {
		return nil
	}
	out := new(ConnectorCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectorCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCatalogSpec) DeepCopyInto(out *ConnectorCatalogSpec) {
	*out = *in
	if in.ConnectorDefinitions != nil {
		in, out := &in.ConnectorDefinitions, &out.ConnectorDefinitions
		*out = make([]ConnectorDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCatalogSpec.
func (in *ConnectorCatalogSpec) DeepCopy() *ConnectorCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorCatalogStatus) DeepCopyInto(out *ConnectorCatalogStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorCatalogStatus.
func (in *ConnectorCatalogStatus) DeepCopy() *ConnectorCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorDefinition) DeepCopyInto(out *ConnectorDefinition) {
	*out = *in
	if in.ConfigFieldDefinitions != nil {
		in, out := &in.ConfigFieldDefinitions, &out.ConfigFieldDefinitions
		*out = make([]ConfigFieldDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorDefinition.
func (in *ConnectorDefinition) DeepCopy() *ConnectorDefinition {
	if in == nil {
		return nil
	}
	out := new(ConnectorDefinition)
	in.DeepCopyInto(out)
	return out
}
