/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The &#x60;Status&#x60; of a given &#x60;Condition&#x60; and the &#x60;Action&#x60; needed to reach the &#x60;Status&#x60;
 */
@ApiModel(description = "The `Status` of a given `Condition` and the `Action` needed to reach the `Status`")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceStatusConditions {
    public static final String SERIALIZED_NAME_ACTION = "action";
    @SerializedName(SERIALIZED_NAME_ACTION)
    private String action;

    public static final String SERIALIZED_NAME_CONDITION = "condition";
    @SerializedName(SERIALIZED_NAME_CONDITION)
    private String condition;

    public static final String SERIALIZED_NAME_STATUS = "status";
    @SerializedName(SERIALIZED_NAME_STATUS)
    private String status;


    public V1alpha1SourceStatusConditions action(String action) {

        this.action = action;
        return this;
    }

    /**
     * Get action
     * @return action
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getAction() {
        return action;
    }


    public void setAction(String action) {
        this.action = action;
    }


    public V1alpha1SourceStatusConditions condition(String condition) {

        this.condition = condition;
        return this;
    }

    /**
     * Get condition
     * @return condition
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getCondition() {
        return condition;
    }


    public void setCondition(String condition) {
        this.condition = condition;
    }


    public V1alpha1SourceStatusConditions status(String status) {

        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getStatus() {
        return status;
    }


    public void setStatus(String status) {
        this.status = status;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceStatusConditions v1alpha1SourceStatusConditions = (V1alpha1SourceStatusConditions) o;
        return Objects.equals(this.action, v1alpha1SourceStatusConditions.action) &&
                Objects.equals(this.condition, v1alpha1SourceStatusConditions.condition) &&
                Objects.equals(this.status, v1alpha1SourceStatusConditions.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(action, condition, status);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceStatusConditions {\n");
        sb.append("    action: ").append(toIndentedString(action)).append("\n");
        sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

