/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1alpha1SourceSpecPython
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecPython {
    public static final String SERIALIZED_NAME_PY = "py";
    @SerializedName(SERIALIZED_NAME_PY)
    private String py;

    public static final String SERIALIZED_NAME_PY_LOCATION = "pyLocation";
    @SerializedName(SERIALIZED_NAME_PY_LOCATION)
    private String pyLocation;


    public V1alpha1SourceSpecPython py(String py) {

        this.py = py;
        return this;
    }

    /**
     * Get py
     * @return py
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPy() {
        return py;
    }


    public void setPy(String py) {
        this.py = py;
    }


    public V1alpha1SourceSpecPython pyLocation(String pyLocation) {

        this.pyLocation = pyLocation;
        return this;
    }

    /**
     * Get pyLocation
     * @return pyLocation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getPyLocation() {
        return pyLocation;
    }


    public void setPyLocation(String pyLocation) {
        this.pyLocation = pyLocation;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecPython v1alpha1SourceSpecPython = (V1alpha1SourceSpecPython) o;
        return Objects.equals(this.py, v1alpha1SourceSpecPython.py) &&
                Objects.equals(this.pyLocation, v1alpha1SourceSpecPython.pyLocation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(py, pyLocation);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecPython {\n");
        sb.append("    py: ").append(toIndentedString(py)).append("\n");
        sb.append("    pyLocation: ").append(toIndentedString(pyLocation)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

