/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DownwardAPIVolumeFile represents information to create the file containing the pod field
 */
@ApiModel(description = "DownwardAPIVolumeFile represents information to create the file containing the pod field")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecPodDownwardAPIItems {
    public static final String SERIALIZED_NAME_FIELD_REF = "fieldRef";
    @SerializedName(SERIALIZED_NAME_FIELD_REF)
    private V1alpha1SourceSpecPodDownwardAPIFieldRef fieldRef;

    public static final String SERIALIZED_NAME_MODE = "mode";
    @SerializedName(SERIALIZED_NAME_MODE)
    private Integer mode;

    public static final String SERIALIZED_NAME_PATH = "path";
    @SerializedName(SERIALIZED_NAME_PATH)
    private String path;

    public static final String SERIALIZED_NAME_RESOURCE_FIELD_REF = "resourceFieldRef";
    @SerializedName(SERIALIZED_NAME_RESOURCE_FIELD_REF)
    private V1alpha1SourceSpecPodDownwardAPIResourceFieldRef resourceFieldRef;


    public V1alpha1SourceSpecPodDownwardAPIItems fieldRef(V1alpha1SourceSpecPodDownwardAPIFieldRef fieldRef) {

        this.fieldRef = fieldRef;
        return this;
    }

    /**
     * Get fieldRef
     * @return fieldRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodDownwardAPIFieldRef getFieldRef() {
        return fieldRef;
    }


    public void setFieldRef(V1alpha1SourceSpecPodDownwardAPIFieldRef fieldRef) {
        this.fieldRef = fieldRef;
    }


    public V1alpha1SourceSpecPodDownwardAPIItems mode(Integer mode) {

        this.mode = mode;
        return this;
    }

    /**
     * Optional: mode bits to use on this file, must be a value between 0 and 0777. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
     * @return mode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Optional: mode bits to use on this file, must be a value between 0 and 0777. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.")

    public Integer getMode() {
        return mode;
    }


    public void setMode(Integer mode) {
        this.mode = mode;
    }


    public V1alpha1SourceSpecPodDownwardAPIItems path(String path) {

        this.path = path;
        return this;
    }

    /**
     * Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the &#39;..&#39; path. Must be utf-8 encoded. The first item of the relative path must not start with &#39;..&#39;
     * @return path
     **/
    @ApiModelProperty(required = true, value = "Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'")

    public String getPath() {
        return path;
    }


    public void setPath(String path) {
        this.path = path;
    }


    public V1alpha1SourceSpecPodDownwardAPIItems resourceFieldRef(V1alpha1SourceSpecPodDownwardAPIResourceFieldRef resourceFieldRef) {

        this.resourceFieldRef = resourceFieldRef;
        return this;
    }

    /**
     * Get resourceFieldRef
     * @return resourceFieldRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodDownwardAPIResourceFieldRef getResourceFieldRef() {
        return resourceFieldRef;
    }


    public void setResourceFieldRef(V1alpha1SourceSpecPodDownwardAPIResourceFieldRef resourceFieldRef) {
        this.resourceFieldRef = resourceFieldRef;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecPodDownwardAPIItems v1alpha1SourceSpecPodDownwardAPIItems = (V1alpha1SourceSpecPodDownwardAPIItems) o;
        return Objects.equals(this.fieldRef, v1alpha1SourceSpecPodDownwardAPIItems.fieldRef) &&
                Objects.equals(this.mode, v1alpha1SourceSpecPodDownwardAPIItems.mode) &&
                Objects.equals(this.path, v1alpha1SourceSpecPodDownwardAPIItems.path) &&
                Objects.equals(this.resourceFieldRef, v1alpha1SourceSpecPodDownwardAPIItems.resourceFieldRef);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fieldRef, mode, path, resourceFieldRef);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecPodDownwardAPIItems {\n");
        sb.append("    fieldRef: ").append(toIndentedString(fieldRef)).append("\n");
        sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
        sb.append("    path: ").append(toIndentedString(path)).append("\n");
        sb.append("    resourceFieldRef: ").append(toIndentedString(resourceFieldRef)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

