/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Volume represents a named volume in a pod that may be accessed by any container in the pod.
 */
@ApiModel(description = "Volume represents a named volume in a pod that may be accessed by any container in the pod.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecPodVolumes {
    public static final String SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE = "awsElasticBlockStore";
    @SerializedName(SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE)
    private V1alpha1SourceSpecPodAwsElasticBlockStore awsElasticBlockStore;

    public static final String SERIALIZED_NAME_AZURE_DISK = "azureDisk";
    @SerializedName(SERIALIZED_NAME_AZURE_DISK)
    private V1alpha1SourceSpecPodAzureDisk azureDisk;

    public static final String SERIALIZED_NAME_AZURE_FILE = "azureFile";
    @SerializedName(SERIALIZED_NAME_AZURE_FILE)
    private V1alpha1SourceSpecPodAzureFile azureFile;

    public static final String SERIALIZED_NAME_CEPHFS = "cephfs";
    @SerializedName(SERIALIZED_NAME_CEPHFS)
    private V1alpha1SourceSpecPodCephfs cephfs;

    public static final String SERIALIZED_NAME_CINDER = "cinder";
    @SerializedName(SERIALIZED_NAME_CINDER)
    private V1alpha1SourceSpecPodCinder cinder;

    public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
    @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
    private V1alpha1SourceSpecPodConfigMap configMap;

    public static final String SERIALIZED_NAME_CSI = "csi";
    @SerializedName(SERIALIZED_NAME_CSI)
    private V1alpha1SourceSpecPodCsi csi;

    public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
    @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
    private V1alpha1SourceSpecPodDownwardAPI downwardAPI;

    public static final String SERIALIZED_NAME_EMPTY_DIR = "emptyDir";
    @SerializedName(SERIALIZED_NAME_EMPTY_DIR)
    private V1alpha1SourceSpecPodEmptyDir emptyDir;

    public static final String SERIALIZED_NAME_FC = "fc";
    @SerializedName(SERIALIZED_NAME_FC)
    private V1alpha1SourceSpecPodFc fc;

    public static final String SERIALIZED_NAME_FLEX_VOLUME = "flexVolume";
    @SerializedName(SERIALIZED_NAME_FLEX_VOLUME)
    private V1alpha1SourceSpecPodFlexVolume flexVolume;

    public static final String SERIALIZED_NAME_FLOCKER = "flocker";
    @SerializedName(SERIALIZED_NAME_FLOCKER)
    private V1alpha1SourceSpecPodFlocker flocker;

    public static final String SERIALIZED_NAME_GCE_PERSISTENT_DISK = "gcePersistentDisk";
    @SerializedName(SERIALIZED_NAME_GCE_PERSISTENT_DISK)
    private V1alpha1SourceSpecPodGcePersistentDisk gcePersistentDisk;

    public static final String SERIALIZED_NAME_GIT_REPO = "gitRepo";
    @SerializedName(SERIALIZED_NAME_GIT_REPO)
    private V1alpha1SourceSpecPodGitRepo gitRepo;

    public static final String SERIALIZED_NAME_GLUSTERFS = "glusterfs";
    @SerializedName(SERIALIZED_NAME_GLUSTERFS)
    private V1alpha1SourceSpecPodGlusterfs glusterfs;

    public static final String SERIALIZED_NAME_HOST_PATH = "hostPath";
    @SerializedName(SERIALIZED_NAME_HOST_PATH)
    private V1alpha1SourceSpecPodHostPath hostPath;

    public static final String SERIALIZED_NAME_ISCSI = "iscsi";
    @SerializedName(SERIALIZED_NAME_ISCSI)
    private V1alpha1SourceSpecPodIscsi iscsi;

    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;

    public static final String SERIALIZED_NAME_NFS = "nfs";
    @SerializedName(SERIALIZED_NAME_NFS)
    private V1alpha1SourceSpecPodNfs nfs;

    public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM = "persistentVolumeClaim";
    @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM)
    private V1alpha1SourceSpecPodPersistentVolumeClaim persistentVolumeClaim;

    public static final String SERIALIZED_NAME_PHOTON_PERSISTENT_DISK = "photonPersistentDisk";
    @SerializedName(SERIALIZED_NAME_PHOTON_PERSISTENT_DISK)
    private V1alpha1SourceSpecPodPhotonPersistentDisk photonPersistentDisk;

    public static final String SERIALIZED_NAME_PORTWORX_VOLUME = "portworxVolume";
    @SerializedName(SERIALIZED_NAME_PORTWORX_VOLUME)
    private V1alpha1SourceSpecPodPortworxVolume portworxVolume;

    public static final String SERIALIZED_NAME_PROJECTED = "projected";
    @SerializedName(SERIALIZED_NAME_PROJECTED)
    private V1alpha1SourceSpecPodProjected projected;

    public static final String SERIALIZED_NAME_QUOBYTE = "quobyte";
    @SerializedName(SERIALIZED_NAME_QUOBYTE)
    private V1alpha1SourceSpecPodQuobyte quobyte;

    public static final String SERIALIZED_NAME_RBD = "rbd";
    @SerializedName(SERIALIZED_NAME_RBD)
    private V1alpha1SourceSpecPodRbd rbd;

    public static final String SERIALIZED_NAME_SCALE_I_O = "scaleIO";
    @SerializedName(SERIALIZED_NAME_SCALE_I_O)
    private V1alpha1SourceSpecPodScaleIO scaleIO;

    public static final String SERIALIZED_NAME_SECRET = "secret";
    @SerializedName(SERIALIZED_NAME_SECRET)
    private V1alpha1SourceSpecPodSecret secret;

    public static final String SERIALIZED_NAME_STORAGEOS = "storageos";
    @SerializedName(SERIALIZED_NAME_STORAGEOS)
    private V1alpha1SourceSpecPodStorageos storageos;

    public static final String SERIALIZED_NAME_VSPHERE_VOLUME = "vsphereVolume";
    @SerializedName(SERIALIZED_NAME_VSPHERE_VOLUME)
    private V1alpha1SourceSpecPodVsphereVolume vsphereVolume;


    public V1alpha1SourceSpecPodVolumes awsElasticBlockStore(V1alpha1SourceSpecPodAwsElasticBlockStore awsElasticBlockStore) {

        this.awsElasticBlockStore = awsElasticBlockStore;
        return this;
    }

    /**
     * Get awsElasticBlockStore
     * @return awsElasticBlockStore
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodAwsElasticBlockStore getAwsElasticBlockStore() {
        return awsElasticBlockStore;
    }


    public void setAwsElasticBlockStore(V1alpha1SourceSpecPodAwsElasticBlockStore awsElasticBlockStore) {
        this.awsElasticBlockStore = awsElasticBlockStore;
    }


    public V1alpha1SourceSpecPodVolumes azureDisk(V1alpha1SourceSpecPodAzureDisk azureDisk) {

        this.azureDisk = azureDisk;
        return this;
    }

    /**
     * Get azureDisk
     * @return azureDisk
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodAzureDisk getAzureDisk() {
        return azureDisk;
    }


    public void setAzureDisk(V1alpha1SourceSpecPodAzureDisk azureDisk) {
        this.azureDisk = azureDisk;
    }


    public V1alpha1SourceSpecPodVolumes azureFile(V1alpha1SourceSpecPodAzureFile azureFile) {

        this.azureFile = azureFile;
        return this;
    }

    /**
     * Get azureFile
     * @return azureFile
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodAzureFile getAzureFile() {
        return azureFile;
    }


    public void setAzureFile(V1alpha1SourceSpecPodAzureFile azureFile) {
        this.azureFile = azureFile;
    }


    public V1alpha1SourceSpecPodVolumes cephfs(V1alpha1SourceSpecPodCephfs cephfs) {

        this.cephfs = cephfs;
        return this;
    }

    /**
     * Get cephfs
     * @return cephfs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodCephfs getCephfs() {
        return cephfs;
    }


    public void setCephfs(V1alpha1SourceSpecPodCephfs cephfs) {
        this.cephfs = cephfs;
    }


    public V1alpha1SourceSpecPodVolumes cinder(V1alpha1SourceSpecPodCinder cinder) {

        this.cinder = cinder;
        return this;
    }

    /**
     * Get cinder
     * @return cinder
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodCinder getCinder() {
        return cinder;
    }


    public void setCinder(V1alpha1SourceSpecPodCinder cinder) {
        this.cinder = cinder;
    }


    public V1alpha1SourceSpecPodVolumes configMap(V1alpha1SourceSpecPodConfigMap configMap) {

        this.configMap = configMap;
        return this;
    }

    /**
     * Get configMap
     * @return configMap
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodConfigMap getConfigMap() {
        return configMap;
    }


    public void setConfigMap(V1alpha1SourceSpecPodConfigMap configMap) {
        this.configMap = configMap;
    }


    public V1alpha1SourceSpecPodVolumes csi(V1alpha1SourceSpecPodCsi csi) {

        this.csi = csi;
        return this;
    }

    /**
     * Get csi
     * @return csi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodCsi getCsi() {
        return csi;
    }


    public void setCsi(V1alpha1SourceSpecPodCsi csi) {
        this.csi = csi;
    }


    public V1alpha1SourceSpecPodVolumes downwardAPI(V1alpha1SourceSpecPodDownwardAPI downwardAPI) {

        this.downwardAPI = downwardAPI;
        return this;
    }

    /**
     * Get downwardAPI
     * @return downwardAPI
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodDownwardAPI getDownwardAPI() {
        return downwardAPI;
    }


    public void setDownwardAPI(V1alpha1SourceSpecPodDownwardAPI downwardAPI) {
        this.downwardAPI = downwardAPI;
    }


    public V1alpha1SourceSpecPodVolumes emptyDir(V1alpha1SourceSpecPodEmptyDir emptyDir) {

        this.emptyDir = emptyDir;
        return this;
    }

    /**
     * Get emptyDir
     * @return emptyDir
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodEmptyDir getEmptyDir() {
        return emptyDir;
    }


    public void setEmptyDir(V1alpha1SourceSpecPodEmptyDir emptyDir) {
        this.emptyDir = emptyDir;
    }


    public V1alpha1SourceSpecPodVolumes fc(V1alpha1SourceSpecPodFc fc) {

        this.fc = fc;
        return this;
    }

    /**
     * Get fc
     * @return fc
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodFc getFc() {
        return fc;
    }


    public void setFc(V1alpha1SourceSpecPodFc fc) {
        this.fc = fc;
    }


    public V1alpha1SourceSpecPodVolumes flexVolume(V1alpha1SourceSpecPodFlexVolume flexVolume) {

        this.flexVolume = flexVolume;
        return this;
    }

    /**
     * Get flexVolume
     * @return flexVolume
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodFlexVolume getFlexVolume() {
        return flexVolume;
    }


    public void setFlexVolume(V1alpha1SourceSpecPodFlexVolume flexVolume) {
        this.flexVolume = flexVolume;
    }


    public V1alpha1SourceSpecPodVolumes flocker(V1alpha1SourceSpecPodFlocker flocker) {

        this.flocker = flocker;
        return this;
    }

    /**
     * Get flocker
     * @return flocker
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodFlocker getFlocker() {
        return flocker;
    }


    public void setFlocker(V1alpha1SourceSpecPodFlocker flocker) {
        this.flocker = flocker;
    }


    public V1alpha1SourceSpecPodVolumes gcePersistentDisk(V1alpha1SourceSpecPodGcePersistentDisk gcePersistentDisk) {

        this.gcePersistentDisk = gcePersistentDisk;
        return this;
    }

    /**
     * Get gcePersistentDisk
     * @return gcePersistentDisk
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodGcePersistentDisk getGcePersistentDisk() {
        return gcePersistentDisk;
    }


    public void setGcePersistentDisk(V1alpha1SourceSpecPodGcePersistentDisk gcePersistentDisk) {
        this.gcePersistentDisk = gcePersistentDisk;
    }


    public V1alpha1SourceSpecPodVolumes gitRepo(V1alpha1SourceSpecPodGitRepo gitRepo) {

        this.gitRepo = gitRepo;
        return this;
    }

    /**
     * Get gitRepo
     * @return gitRepo
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodGitRepo getGitRepo() {
        return gitRepo;
    }


    public void setGitRepo(V1alpha1SourceSpecPodGitRepo gitRepo) {
        this.gitRepo = gitRepo;
    }


    public V1alpha1SourceSpecPodVolumes glusterfs(V1alpha1SourceSpecPodGlusterfs glusterfs) {

        this.glusterfs = glusterfs;
        return this;
    }

    /**
     * Get glusterfs
     * @return glusterfs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodGlusterfs getGlusterfs() {
        return glusterfs;
    }


    public void setGlusterfs(V1alpha1SourceSpecPodGlusterfs glusterfs) {
        this.glusterfs = glusterfs;
    }


    public V1alpha1SourceSpecPodVolumes hostPath(V1alpha1SourceSpecPodHostPath hostPath) {

        this.hostPath = hostPath;
        return this;
    }

    /**
     * Get hostPath
     * @return hostPath
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodHostPath getHostPath() {
        return hostPath;
    }


    public void setHostPath(V1alpha1SourceSpecPodHostPath hostPath) {
        this.hostPath = hostPath;
    }


    public V1alpha1SourceSpecPodVolumes iscsi(V1alpha1SourceSpecPodIscsi iscsi) {

        this.iscsi = iscsi;
        return this;
    }

    /**
     * Get iscsi
     * @return iscsi
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodIscsi getIscsi() {
        return iscsi;
    }


    public void setIscsi(V1alpha1SourceSpecPodIscsi iscsi) {
        this.iscsi = iscsi;
    }


    public V1alpha1SourceSpecPodVolumes name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Volume&#39;s name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
     * @return name
     **/
    @ApiModelProperty(required = true, value = "Volume's name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    public V1alpha1SourceSpecPodVolumes nfs(V1alpha1SourceSpecPodNfs nfs) {

        this.nfs = nfs;
        return this;
    }

    /**
     * Get nfs
     * @return nfs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodNfs getNfs() {
        return nfs;
    }


    public void setNfs(V1alpha1SourceSpecPodNfs nfs) {
        this.nfs = nfs;
    }


    public V1alpha1SourceSpecPodVolumes persistentVolumeClaim(V1alpha1SourceSpecPodPersistentVolumeClaim persistentVolumeClaim) {

        this.persistentVolumeClaim = persistentVolumeClaim;
        return this;
    }

    /**
     * Get persistentVolumeClaim
     * @return persistentVolumeClaim
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodPersistentVolumeClaim getPersistentVolumeClaim() {
        return persistentVolumeClaim;
    }


    public void setPersistentVolumeClaim(V1alpha1SourceSpecPodPersistentVolumeClaim persistentVolumeClaim) {
        this.persistentVolumeClaim = persistentVolumeClaim;
    }


    public V1alpha1SourceSpecPodVolumes photonPersistentDisk(V1alpha1SourceSpecPodPhotonPersistentDisk photonPersistentDisk) {

        this.photonPersistentDisk = photonPersistentDisk;
        return this;
    }

    /**
     * Get photonPersistentDisk
     * @return photonPersistentDisk
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodPhotonPersistentDisk getPhotonPersistentDisk() {
        return photonPersistentDisk;
    }


    public void setPhotonPersistentDisk(V1alpha1SourceSpecPodPhotonPersistentDisk photonPersistentDisk) {
        this.photonPersistentDisk = photonPersistentDisk;
    }


    public V1alpha1SourceSpecPodVolumes portworxVolume(V1alpha1SourceSpecPodPortworxVolume portworxVolume) {

        this.portworxVolume = portworxVolume;
        return this;
    }

    /**
     * Get portworxVolume
     * @return portworxVolume
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodPortworxVolume getPortworxVolume() {
        return portworxVolume;
    }


    public void setPortworxVolume(V1alpha1SourceSpecPodPortworxVolume portworxVolume) {
        this.portworxVolume = portworxVolume;
    }


    public V1alpha1SourceSpecPodVolumes projected(V1alpha1SourceSpecPodProjected projected) {

        this.projected = projected;
        return this;
    }

    /**
     * Get projected
     * @return projected
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodProjected getProjected() {
        return projected;
    }


    public void setProjected(V1alpha1SourceSpecPodProjected projected) {
        this.projected = projected;
    }


    public V1alpha1SourceSpecPodVolumes quobyte(V1alpha1SourceSpecPodQuobyte quobyte) {

        this.quobyte = quobyte;
        return this;
    }

    /**
     * Get quobyte
     * @return quobyte
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodQuobyte getQuobyte() {
        return quobyte;
    }


    public void setQuobyte(V1alpha1SourceSpecPodQuobyte quobyte) {
        this.quobyte = quobyte;
    }


    public V1alpha1SourceSpecPodVolumes rbd(V1alpha1SourceSpecPodRbd rbd) {

        this.rbd = rbd;
        return this;
    }

    /**
     * Get rbd
     * @return rbd
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodRbd getRbd() {
        return rbd;
    }


    public void setRbd(V1alpha1SourceSpecPodRbd rbd) {
        this.rbd = rbd;
    }


    public V1alpha1SourceSpecPodVolumes scaleIO(V1alpha1SourceSpecPodScaleIO scaleIO) {

        this.scaleIO = scaleIO;
        return this;
    }

    /**
     * Get scaleIO
     * @return scaleIO
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodScaleIO getScaleIO() {
        return scaleIO;
    }


    public void setScaleIO(V1alpha1SourceSpecPodScaleIO scaleIO) {
        this.scaleIO = scaleIO;
    }


    public V1alpha1SourceSpecPodVolumes secret(V1alpha1SourceSpecPodSecret secret) {

        this.secret = secret;
        return this;
    }

    /**
     * Get secret
     * @return secret
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodSecret getSecret() {
        return secret;
    }


    public void setSecret(V1alpha1SourceSpecPodSecret secret) {
        this.secret = secret;
    }


    public V1alpha1SourceSpecPodVolumes storageos(V1alpha1SourceSpecPodStorageos storageos) {

        this.storageos = storageos;
        return this;
    }

    /**
     * Get storageos
     * @return storageos
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodStorageos getStorageos() {
        return storageos;
    }


    public void setStorageos(V1alpha1SourceSpecPodStorageos storageos) {
        this.storageos = storageos;
    }


    public V1alpha1SourceSpecPodVolumes vsphereVolume(V1alpha1SourceSpecPodVsphereVolume vsphereVolume) {

        this.vsphereVolume = vsphereVolume;
        return this;
    }

    /**
     * Get vsphereVolume
     * @return vsphereVolume
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodVsphereVolume getVsphereVolume() {
        return vsphereVolume;
    }


    public void setVsphereVolume(V1alpha1SourceSpecPodVsphereVolume vsphereVolume) {
        this.vsphereVolume = vsphereVolume;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecPodVolumes v1alpha1SourceSpecPodVolumes = (V1alpha1SourceSpecPodVolumes) o;
        return Objects.equals(this.awsElasticBlockStore, v1alpha1SourceSpecPodVolumes.awsElasticBlockStore) &&
                Objects.equals(this.azureDisk, v1alpha1SourceSpecPodVolumes.azureDisk) &&
                Objects.equals(this.azureFile, v1alpha1SourceSpecPodVolumes.azureFile) &&
                Objects.equals(this.cephfs, v1alpha1SourceSpecPodVolumes.cephfs) &&
                Objects.equals(this.cinder, v1alpha1SourceSpecPodVolumes.cinder) &&
                Objects.equals(this.configMap, v1alpha1SourceSpecPodVolumes.configMap) &&
                Objects.equals(this.csi, v1alpha1SourceSpecPodVolumes.csi) &&
                Objects.equals(this.downwardAPI, v1alpha1SourceSpecPodVolumes.downwardAPI) &&
                Objects.equals(this.emptyDir, v1alpha1SourceSpecPodVolumes.emptyDir) &&
                Objects.equals(this.fc, v1alpha1SourceSpecPodVolumes.fc) &&
                Objects.equals(this.flexVolume, v1alpha1SourceSpecPodVolumes.flexVolume) &&
                Objects.equals(this.flocker, v1alpha1SourceSpecPodVolumes.flocker) &&
                Objects.equals(this.gcePersistentDisk, v1alpha1SourceSpecPodVolumes.gcePersistentDisk) &&
                Objects.equals(this.gitRepo, v1alpha1SourceSpecPodVolumes.gitRepo) &&
                Objects.equals(this.glusterfs, v1alpha1SourceSpecPodVolumes.glusterfs) &&
                Objects.equals(this.hostPath, v1alpha1SourceSpecPodVolumes.hostPath) &&
                Objects.equals(this.iscsi, v1alpha1SourceSpecPodVolumes.iscsi) &&
                Objects.equals(this.name, v1alpha1SourceSpecPodVolumes.name) &&
                Objects.equals(this.nfs, v1alpha1SourceSpecPodVolumes.nfs) &&
                Objects.equals(this.persistentVolumeClaim, v1alpha1SourceSpecPodVolumes.persistentVolumeClaim) &&
                Objects.equals(this.photonPersistentDisk, v1alpha1SourceSpecPodVolumes.photonPersistentDisk) &&
                Objects.equals(this.portworxVolume, v1alpha1SourceSpecPodVolumes.portworxVolume) &&
                Objects.equals(this.projected, v1alpha1SourceSpecPodVolumes.projected) &&
                Objects.equals(this.quobyte, v1alpha1SourceSpecPodVolumes.quobyte) &&
                Objects.equals(this.rbd, v1alpha1SourceSpecPodVolumes.rbd) &&
                Objects.equals(this.scaleIO, v1alpha1SourceSpecPodVolumes.scaleIO) &&
                Objects.equals(this.secret, v1alpha1SourceSpecPodVolumes.secret) &&
                Objects.equals(this.storageos, v1alpha1SourceSpecPodVolumes.storageos) &&
                Objects.equals(this.vsphereVolume, v1alpha1SourceSpecPodVolumes.vsphereVolume);
    }

    @Override
    public int hashCode() {
        return Objects.hash(awsElasticBlockStore, azureDisk, azureFile, cephfs, cinder, configMap, csi, downwardAPI, emptyDir, fc, flexVolume, flocker, gcePersistentDisk, gitRepo, glusterfs, hostPath, iscsi, name, nfs, persistentVolumeClaim, photonPersistentDisk, portworxVolume, projected, quobyte, rbd, scaleIO, secret, storageos, vsphereVolume);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecPodVolumes {\n");
        sb.append("    awsElasticBlockStore: ").append(toIndentedString(awsElasticBlockStore)).append("\n");
        sb.append("    azureDisk: ").append(toIndentedString(azureDisk)).append("\n");
        sb.append("    azureFile: ").append(toIndentedString(azureFile)).append("\n");
        sb.append("    cephfs: ").append(toIndentedString(cephfs)).append("\n");
        sb.append("    cinder: ").append(toIndentedString(cinder)).append("\n");
        sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
        sb.append("    csi: ").append(toIndentedString(csi)).append("\n");
        sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
        sb.append("    emptyDir: ").append(toIndentedString(emptyDir)).append("\n");
        sb.append("    fc: ").append(toIndentedString(fc)).append("\n");
        sb.append("    flexVolume: ").append(toIndentedString(flexVolume)).append("\n");
        sb.append("    flocker: ").append(toIndentedString(flocker)).append("\n");
        sb.append("    gcePersistentDisk: ").append(toIndentedString(gcePersistentDisk)).append("\n");
        sb.append("    gitRepo: ").append(toIndentedString(gitRepo)).append("\n");
        sb.append("    glusterfs: ").append(toIndentedString(glusterfs)).append("\n");
        sb.append("    hostPath: ").append(toIndentedString(hostPath)).append("\n");
        sb.append("    iscsi: ").append(toIndentedString(iscsi)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    nfs: ").append(toIndentedString(nfs)).append("\n");
        sb.append("    persistentVolumeClaim: ").append(toIndentedString(persistentVolumeClaim)).append("\n");
        sb.append("    photonPersistentDisk: ").append(toIndentedString(photonPersistentDisk)).append("\n");
        sb.append("    portworxVolume: ").append(toIndentedString(portworxVolume)).append("\n");
        sb.append("    projected: ").append(toIndentedString(projected)).append("\n");
        sb.append("    quobyte: ").append(toIndentedString(quobyte)).append("\n");
        sb.append("    rbd: ").append(toIndentedString(rbd)).append("\n");
        sb.append("    scaleIO: ").append(toIndentedString(scaleIO)).append("\n");
        sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
        sb.append("    storageos: ").append(toIndentedString(storageos)).append("\n");
        sb.append("    vsphereVolume: ").append(toIndentedString(vsphereVolume)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

