/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets {
    public static final String SERIALIZED_NAME_AS_VOLUME = "asVolume";
    @SerializedName(SERIALIZED_NAME_AS_VOLUME)
    private String asVolume;

    public static final String SERIALIZED_NAME_SECRET_KEY = "secretKey";
    @SerializedName(SERIALIZED_NAME_SECRET_KEY)
    private String secretKey;

    public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
    @SerializedName(SERIALIZED_NAME_SECRET_NAME)
    private String secretName;


    public V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets asVolume(String asVolume) {

        this.asVolume = asVolume;
        return this;
    }

    /**
     * Get asVolume
     * @return asVolume
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getAsVolume() {
        return asVolume;
    }


    public void setAsVolume(String asVolume) {
        this.asVolume = asVolume;
    }


    public V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets secretKey(String secretKey) {

        this.secretKey = secretKey;
        return this;
    }

    /**
     * Get secretKey
     * @return secretKey
     **/
    @ApiModelProperty(required = true, value = "")

    public String getSecretKey() {
        return secretKey;
    }


    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }


    public V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets secretName(String secretName) {

        this.secretName = secretName;
        return this;
    }

    /**
     * Get secretName
     * @return secretName
     **/
    @ApiModelProperty(required = true, value = "")

    public String getSecretName() {
        return secretName;
    }


    public void setSecretName(String secretName) {
        this.secretName = secretName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets v1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets = (V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets) o;
        return Objects.equals(this.asVolume, v1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets.asVolume) &&
                Objects.equals(this.secretKey, v1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets.secretKey) &&
                Objects.equals(this.secretName, v1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets.secretName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(asVolume, secretKey, secretName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecOutputProducerConfCryptoConfigCryptoSecrets {\n");
        sb.append("    asVolume: ").append(toIndentedString(asVolume)).append("\n");
        sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");
        sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

