/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1alpha1SourceSpecGolang
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecGolang {
    public static final String SERIALIZED_NAME_GO = "go";
    @SerializedName(SERIALIZED_NAME_GO)
    private String go;

    public static final String SERIALIZED_NAME_GO_LOCATION = "goLocation";
    @SerializedName(SERIALIZED_NAME_GO_LOCATION)
    private String goLocation;


    public V1alpha1SourceSpecGolang go(String go) {

        this.go = go;
        return this;
    }

    /**
     * Get go
     * @return go
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getGo() {
        return go;
    }


    public void setGo(String go) {
        this.go = go;
    }


    public V1alpha1SourceSpecGolang goLocation(String goLocation) {

        this.goLocation = goLocation;
        return this;
    }

    /**
     * Get goLocation
     * @return goLocation
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getGoLocation() {
        return goLocation;
    }


    public void setGoLocation(String goLocation) {
        this.goLocation = goLocation;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecGolang v1alpha1SourceSpecGolang = (V1alpha1SourceSpecGolang) o;
        return Objects.equals(this.go, v1alpha1SourceSpecGolang.go) &&
                Objects.equals(this.goLocation, v1alpha1SourceSpecGolang.goLocation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(go, goLocation);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecGolang {\n");
        sb.append("    go: ").append(toIndentedString(go)).append("\n");
        sb.append("    goLocation: ").append(toIndentedString(goLocation)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

