/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The Windows specific settings applied to all containers. If unspecified, the options within a container&#39;s SecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
 */
@ApiModel(description = "The Windows specific settings applied to all containers. If unspecified, the options within a container's SecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecPodSecurityContextWindowsOptions {
    public static final String SERIALIZED_NAME_GMSA_CREDENTIAL_SPEC = "gmsaCredentialSpec";
    @SerializedName(SERIALIZED_NAME_GMSA_CREDENTIAL_SPEC)
    private String gmsaCredentialSpec;

    public static final String SERIALIZED_NAME_GMSA_CREDENTIAL_SPEC_NAME = "gmsaCredentialSpecName";
    @SerializedName(SERIALIZED_NAME_GMSA_CREDENTIAL_SPEC_NAME)
    private String gmsaCredentialSpecName;

    public static final String SERIALIZED_NAME_RUN_AS_USER_NAME = "runAsUserName";
    @SerializedName(SERIALIZED_NAME_RUN_AS_USER_NAME)
    private String runAsUserName;


    public V1alpha1SourceSpecPodSecurityContextWindowsOptions gmsaCredentialSpec(String gmsaCredentialSpec) {

        this.gmsaCredentialSpec = gmsaCredentialSpec;
        return this;
    }

    /**
     * GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
     * @return gmsaCredentialSpec
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.")

    public String getGmsaCredentialSpec() {
        return gmsaCredentialSpec;
    }


    public void setGmsaCredentialSpec(String gmsaCredentialSpec) {
        this.gmsaCredentialSpec = gmsaCredentialSpec;
    }


    public V1alpha1SourceSpecPodSecurityContextWindowsOptions gmsaCredentialSpecName(String gmsaCredentialSpecName) {

        this.gmsaCredentialSpecName = gmsaCredentialSpecName;
        return this;
    }

    /**
     * GMSACredentialSpecName is the name of the GMSA credential spec to use.
     * @return gmsaCredentialSpecName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "GMSACredentialSpecName is the name of the GMSA credential spec to use.")

    public String getGmsaCredentialSpecName() {
        return gmsaCredentialSpecName;
    }


    public void setGmsaCredentialSpecName(String gmsaCredentialSpecName) {
        this.gmsaCredentialSpecName = gmsaCredentialSpecName;
    }


    public V1alpha1SourceSpecPodSecurityContextWindowsOptions runAsUserName(String runAsUserName) {

        this.runAsUserName = runAsUserName;
        return this;
    }

    /**
     * The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
     * @return runAsUserName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.")

    public String getRunAsUserName() {
        return runAsUserName;
    }


    public void setRunAsUserName(String runAsUserName) {
        this.runAsUserName = runAsUserName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecPodSecurityContextWindowsOptions v1alpha1SourceSpecPodSecurityContextWindowsOptions = (V1alpha1SourceSpecPodSecurityContextWindowsOptions) o;
        return Objects.equals(this.gmsaCredentialSpec, v1alpha1SourceSpecPodSecurityContextWindowsOptions.gmsaCredentialSpec) &&
                Objects.equals(this.gmsaCredentialSpecName, v1alpha1SourceSpecPodSecurityContextWindowsOptions.gmsaCredentialSpecName) &&
                Objects.equals(this.runAsUserName, v1alpha1SourceSpecPodSecurityContextWindowsOptions.runAsUserName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(gmsaCredentialSpec, gmsaCredentialSpecName, runAsUserName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecPodSecurityContextWindowsOptions {\n");
        sb.append("    gmsaCredentialSpec: ").append(toIndentedString(gmsaCredentialSpec)).append("\n");
        sb.append("    gmsaCredentialSpecName: ").append(toIndentedString(gmsaCredentialSpecName)).append("\n");
        sb.append("    runAsUserName: ").append(toIndentedString(runAsUserName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

