/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Projection that may be projected along with other supported volume types
 */
@ApiModel(description = "Projection that may be projected along with other supported volume types")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecPodProjectedSources {
    public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
    @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
    private V1alpha1SourceSpecPodProjectedConfigMap configMap;

    public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
    @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
    private V1alpha1SourceSpecPodProjectedDownwardAPI downwardAPI;

    public static final String SERIALIZED_NAME_SECRET = "secret";
    @SerializedName(SERIALIZED_NAME_SECRET)
    private V1alpha1SourceSpecPodProjectedSecret secret;

    public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_TOKEN = "serviceAccountToken";
    @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_TOKEN)
    private V1alpha1SourceSpecPodProjectedServiceAccountToken serviceAccountToken;


    public V1alpha1SourceSpecPodProjectedSources configMap(V1alpha1SourceSpecPodProjectedConfigMap configMap) {

        this.configMap = configMap;
        return this;
    }

    /**
     * Get configMap
     * @return configMap
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodProjectedConfigMap getConfigMap() {
        return configMap;
    }


    public void setConfigMap(V1alpha1SourceSpecPodProjectedConfigMap configMap) {
        this.configMap = configMap;
    }


    public V1alpha1SourceSpecPodProjectedSources downwardAPI(V1alpha1SourceSpecPodProjectedDownwardAPI downwardAPI) {

        this.downwardAPI = downwardAPI;
        return this;
    }

    /**
     * Get downwardAPI
     * @return downwardAPI
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodProjectedDownwardAPI getDownwardAPI() {
        return downwardAPI;
    }


    public void setDownwardAPI(V1alpha1SourceSpecPodProjectedDownwardAPI downwardAPI) {
        this.downwardAPI = downwardAPI;
    }


    public V1alpha1SourceSpecPodProjectedSources secret(V1alpha1SourceSpecPodProjectedSecret secret) {

        this.secret = secret;
        return this;
    }

    /**
     * Get secret
     * @return secret
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodProjectedSecret getSecret() {
        return secret;
    }


    public void setSecret(V1alpha1SourceSpecPodProjectedSecret secret) {
        this.secret = secret;
    }


    public V1alpha1SourceSpecPodProjectedSources serviceAccountToken(V1alpha1SourceSpecPodProjectedServiceAccountToken serviceAccountToken) {

        this.serviceAccountToken = serviceAccountToken;
        return this;
    }

    /**
     * Get serviceAccountToken
     * @return serviceAccountToken
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodProjectedServiceAccountToken getServiceAccountToken() {
        return serviceAccountToken;
    }


    public void setServiceAccountToken(V1alpha1SourceSpecPodProjectedServiceAccountToken serviceAccountToken) {
        this.serviceAccountToken = serviceAccountToken;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecPodProjectedSources v1alpha1SourceSpecPodProjectedSources = (V1alpha1SourceSpecPodProjectedSources) o;
        return Objects.equals(this.configMap, v1alpha1SourceSpecPodProjectedSources.configMap) &&
                Objects.equals(this.downwardAPI, v1alpha1SourceSpecPodProjectedSources.downwardAPI) &&
                Objects.equals(this.secret, v1alpha1SourceSpecPodProjectedSources.secret) &&
                Objects.equals(this.serviceAccountToken, v1alpha1SourceSpecPodProjectedSources.serviceAccountToken);
    }

    @Override
    public int hashCode() {
        return Objects.hash(configMap, downwardAPI, secret, serviceAccountToken);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecPodProjectedSources {\n");
        sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
        sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
        sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
        sb.append("    serviceAccountToken: ").append(toIndentedString(serviceAccountToken)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

