/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.streamnative.cloud.models.source;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SecurityContext specifies the security context for the entire pod More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context
 */
@ApiModel(description = "SecurityContext specifies the security context for the entire pod More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-02T12:09:25.926Z[Etc/UTC]")
public class V1alpha1SourceSpecPodSecurityContext {
    public static final String SERIALIZED_NAME_FS_GROUP = "fsGroup";
    @SerializedName(SERIALIZED_NAME_FS_GROUP)
    private Long fsGroup;

    public static final String SERIALIZED_NAME_FS_GROUP_CHANGE_POLICY = "fsGroupChangePolicy";
    @SerializedName(SERIALIZED_NAME_FS_GROUP_CHANGE_POLICY)
    private String fsGroupChangePolicy;

    public static final String SERIALIZED_NAME_RUN_AS_GROUP = "runAsGroup";
    @SerializedName(SERIALIZED_NAME_RUN_AS_GROUP)
    private Long runAsGroup;

    public static final String SERIALIZED_NAME_RUN_AS_NON_ROOT = "runAsNonRoot";
    @SerializedName(SERIALIZED_NAME_RUN_AS_NON_ROOT)
    private Boolean runAsNonRoot;

    public static final String SERIALIZED_NAME_RUN_AS_USER = "runAsUser";
    @SerializedName(SERIALIZED_NAME_RUN_AS_USER)
    private Long runAsUser;

    public static final String SERIALIZED_NAME_SE_LINUX_OPTIONS = "seLinuxOptions";
    @SerializedName(SERIALIZED_NAME_SE_LINUX_OPTIONS)
    private V1alpha1SourceSpecPodSecurityContextSeLinuxOptions seLinuxOptions;

    public static final String SERIALIZED_NAME_SUPPLEMENTAL_GROUPS = "supplementalGroups";
    @SerializedName(SERIALIZED_NAME_SUPPLEMENTAL_GROUPS)
    private List<Long> supplementalGroups = null;

    public static final String SERIALIZED_NAME_SYSCTLS = "sysctls";
    @SerializedName(SERIALIZED_NAME_SYSCTLS)
    private List<V1alpha1SourceSpecPodSecurityContextSysctls> sysctls = null;

    public static final String SERIALIZED_NAME_WINDOWS_OPTIONS = "windowsOptions";
    @SerializedName(SERIALIZED_NAME_WINDOWS_OPTIONS)
    private V1alpha1SourceSpecPodSecurityContextWindowsOptions windowsOptions;


    public V1alpha1SourceSpecPodSecurityContext fsGroup(Long fsGroup) {

        this.fsGroup = fsGroup;
        return this;
    }

    /**
     * A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to change the ownership of that volume to be owned by the pod:   1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR&#39;d with rw-rw----   If unset, the Kubelet will not modify the ownership and permissions of any volume.
     * @return fsGroup
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to change the ownership of that volume to be owned by the pod:   1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR'd with rw-rw----   If unset, the Kubelet will not modify the ownership and permissions of any volume.")

    public Long getFsGroup() {
        return fsGroup;
    }


    public void setFsGroup(Long fsGroup) {
        this.fsGroup = fsGroup;
    }


    public V1alpha1SourceSpecPodSecurityContext fsGroupChangePolicy(String fsGroupChangePolicy) {

        this.fsGroupChangePolicy = fsGroupChangePolicy;
        return this;
    }

    /**
     * fsGroupChangePolicy defines behavior of changing ownership and permission of the volume before being exposed inside Pod. This field will only apply to volume types which support fsGroup based ownership(and permissions). It will have no effect on ephemeral volume types such as: secret, configmaps and emptydir. Valid values are \&quot;OnRootMismatch\&quot; and \&quot;Always\&quot;. If not specified defaults to \&quot;Always\&quot;.
     * @return fsGroupChangePolicy
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "fsGroupChangePolicy defines behavior of changing ownership and permission of the volume before being exposed inside Pod. This field will only apply to volume types which support fsGroup based ownership(and permissions). It will have no effect on ephemeral volume types such as: secret, configmaps and emptydir. Valid values are \"OnRootMismatch\" and \"Always\". If not specified defaults to \"Always\".")

    public String getFsGroupChangePolicy() {
        return fsGroupChangePolicy;
    }


    public void setFsGroupChangePolicy(String fsGroupChangePolicy) {
        this.fsGroupChangePolicy = fsGroupChangePolicy;
    }


    public V1alpha1SourceSpecPodSecurityContext runAsGroup(Long runAsGroup) {

        this.runAsGroup = runAsGroup;
        return this;
    }

    /**
     * The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.
     * @return runAsGroup
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.")

    public Long getRunAsGroup() {
        return runAsGroup;
    }


    public void setRunAsGroup(Long runAsGroup) {
        this.runAsGroup = runAsGroup;
    }


    public V1alpha1SourceSpecPodSecurityContext runAsNonRoot(Boolean runAsNonRoot) {

        this.runAsNonRoot = runAsNonRoot;
        return this;
    }

    /**
     * Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
     * @return runAsNonRoot
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.")

    public Boolean getRunAsNonRoot() {
        return runAsNonRoot;
    }


    public void setRunAsNonRoot(Boolean runAsNonRoot) {
        this.runAsNonRoot = runAsNonRoot;
    }


    public V1alpha1SourceSpecPodSecurityContext runAsUser(Long runAsUser) {

        this.runAsUser = runAsUser;
        return this;
    }

    /**
     * The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.
     * @return runAsUser
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.")

    public Long getRunAsUser() {
        return runAsUser;
    }


    public void setRunAsUser(Long runAsUser) {
        this.runAsUser = runAsUser;
    }


    public V1alpha1SourceSpecPodSecurityContext seLinuxOptions(V1alpha1SourceSpecPodSecurityContextSeLinuxOptions seLinuxOptions) {

        this.seLinuxOptions = seLinuxOptions;
        return this;
    }

    /**
     * Get seLinuxOptions
     * @return seLinuxOptions
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodSecurityContextSeLinuxOptions getSeLinuxOptions() {
        return seLinuxOptions;
    }


    public void setSeLinuxOptions(V1alpha1SourceSpecPodSecurityContextSeLinuxOptions seLinuxOptions) {
        this.seLinuxOptions = seLinuxOptions;
    }


    public V1alpha1SourceSpecPodSecurityContext supplementalGroups(List<Long> supplementalGroups) {

        this.supplementalGroups = supplementalGroups;
        return this;
    }

    public V1alpha1SourceSpecPodSecurityContext addSupplementalGroupsItem(Long supplementalGroupsItem) {
        if (this.supplementalGroups == null) {
            this.supplementalGroups = new ArrayList<Long>();
        }
        this.supplementalGroups.add(supplementalGroupsItem);
        return this;
    }

    /**
     * A list of groups applied to the first process run in each container, in addition to the container&#39;s primary GID.  If unspecified, no groups will be added to any container.
     * @return supplementalGroups
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A list of groups applied to the first process run in each container, in addition to the container's primary GID.  If unspecified, no groups will be added to any container.")

    public List<Long> getSupplementalGroups() {
        return supplementalGroups;
    }


    public void setSupplementalGroups(List<Long> supplementalGroups) {
        this.supplementalGroups = supplementalGroups;
    }


    public V1alpha1SourceSpecPodSecurityContext sysctls(List<V1alpha1SourceSpecPodSecurityContextSysctls> sysctls) {

        this.sysctls = sysctls;
        return this;
    }

    public V1alpha1SourceSpecPodSecurityContext addSysctlsItem(V1alpha1SourceSpecPodSecurityContextSysctls sysctlsItem) {
        if (this.sysctls == null) {
            this.sysctls = new ArrayList<V1alpha1SourceSpecPodSecurityContextSysctls>();
        }
        this.sysctls.add(sysctlsItem);
        return this;
    }

    /**
     * Sysctls hold a list of namespaced sysctls used for the pod. Pods with unsupported sysctls (by the container runtime) might fail to launch.
     * @return sysctls
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Sysctls hold a list of namespaced sysctls used for the pod. Pods with unsupported sysctls (by the container runtime) might fail to launch.")

    public List<V1alpha1SourceSpecPodSecurityContextSysctls> getSysctls() {
        return sysctls;
    }


    public void setSysctls(List<V1alpha1SourceSpecPodSecurityContextSysctls> sysctls) {
        this.sysctls = sysctls;
    }


    public V1alpha1SourceSpecPodSecurityContext windowsOptions(V1alpha1SourceSpecPodSecurityContextWindowsOptions windowsOptions) {

        this.windowsOptions = windowsOptions;
        return this;
    }

    /**
     * Get windowsOptions
     * @return windowsOptions
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SourceSpecPodSecurityContextWindowsOptions getWindowsOptions() {
        return windowsOptions;
    }


    public void setWindowsOptions(V1alpha1SourceSpecPodSecurityContextWindowsOptions windowsOptions) {
        this.windowsOptions = windowsOptions;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SourceSpecPodSecurityContext v1alpha1SourceSpecPodSecurityContext = (V1alpha1SourceSpecPodSecurityContext) o;
        return Objects.equals(this.fsGroup, v1alpha1SourceSpecPodSecurityContext.fsGroup) &&
                Objects.equals(this.fsGroupChangePolicy, v1alpha1SourceSpecPodSecurityContext.fsGroupChangePolicy) &&
                Objects.equals(this.runAsGroup, v1alpha1SourceSpecPodSecurityContext.runAsGroup) &&
                Objects.equals(this.runAsNonRoot, v1alpha1SourceSpecPodSecurityContext.runAsNonRoot) &&
                Objects.equals(this.runAsUser, v1alpha1SourceSpecPodSecurityContext.runAsUser) &&
                Objects.equals(this.seLinuxOptions, v1alpha1SourceSpecPodSecurityContext.seLinuxOptions) &&
                Objects.equals(this.supplementalGroups, v1alpha1SourceSpecPodSecurityContext.supplementalGroups) &&
                Objects.equals(this.sysctls, v1alpha1SourceSpecPodSecurityContext.sysctls) &&
                Objects.equals(this.windowsOptions, v1alpha1SourceSpecPodSecurityContext.windowsOptions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fsGroup, fsGroupChangePolicy, runAsGroup, runAsNonRoot, runAsUser, seLinuxOptions, supplementalGroups, sysctls, windowsOptions);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SourceSpecPodSecurityContext {\n");
        sb.append("    fsGroup: ").append(toIndentedString(fsGroup)).append("\n");
        sb.append("    fsGroupChangePolicy: ").append(toIndentedString(fsGroupChangePolicy)).append("\n");
        sb.append("    runAsGroup: ").append(toIndentedString(runAsGroup)).append("\n");
        sb.append("    runAsNonRoot: ").append(toIndentedString(runAsNonRoot)).append("\n");
        sb.append("    runAsUser: ").append(toIndentedString(runAsUser)).append("\n");
        sb.append("    seLinuxOptions: ").append(toIndentedString(seLinuxOptions)).append("\n");
        sb.append("    supplementalGroups: ").append(toIndentedString(supplementalGroups)).append("\n");
        sb.append("    sysctls: ").append(toIndentedString(sysctls)).append("\n");
        sb.append("    windowsOptions: ").append(toIndentedString(windowsOptions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

