{{- $cn := ( include "function-mesh-secrets-webhook.certificate.commonName" . ) -}}
{{- $ca := genCA "function-mesh-admission-ca" 3650 -}}
{{- $cert := genSignedCert $cn nil (list $cn) 3650 $ca -}}
{{- $certCert := $cert.Cert -}}
{{- $certKey := $cert.Key -}}
{{- $caCert := $ca.Cert -}}
{{- $caKey := $ca.Key -}}
apiVersion: v1
data:
  tls.crt: {{ b64enc $certCert }}
  tls.key: {{ b64enc $certKey }}
kind: Secret
metadata:
  name: function-mesh-admission-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "function-mesh-secrets-webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls

---
apiVersion: v1
kind: Secret
metadata:
  name: function-mesh-admission-webhook-server-cert-ca
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "function-mesh-secrets-webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $caCert  }}
  tls.key: {{ b64enc $caKey  }}