resources:
- ../default
- ../samples
- ../scorecard

patches:
  # Hacky way to shrink the size of FunctionMesh crd
  - target:
      kind: CustomResourceDefinition
      name: functionmeshes.compute.functionmesh.io
    patch: |-
      - op: remove
        path: /spec/validation
