apiVersion: compute.functionmesh.io/v1alpha1
kind: BackendConfig
metadata:
  name: global-backend-config
spec:
  autoUpdate: true
  env:
    global1: globalvalue1
    shared1: fromglobal
  pod:
    liveness:
      initialDelaySeconds: 10
      periodSeconds: 30
    labels:
      from: global-backendconfig
    tolerations:
      - key: disktype
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 600
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: disktype
                  operator: In
                  values:
                    - ssd
