name: Precommit - OLM verify
on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'PROJECT'
      - 'LICENSE'
      - 'mesh-worker-service/README.md'
      - 'tools/README.md'
jobs:
  olm-verify:
    name: Verify OLM bundle
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.0
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up GO 1.23.0
        uses: actions/setup-go@v1
        with:
          go-version: 1.23.0
        id: go

      - name: InstallKubebuilder
        run: |
          curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.6.0/kubebuilder_linux_amd64"
          chmod +x kubebuilder && mv kubebuilder /usr/local/bin/

      - name: Install operator-sdk
        run: |
          RELEASE_VERSION=v1.29.0
          curl -LO "https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64"
          chmod +x operator-sdk_linux_amd64 && sudo mkdir -p /usr/local/bin/ && sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

      - name: Set up yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.30.4/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --help

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        with:
          node_image: kindest/node:v1.23.17

      - name: Build RedHat certificated bundle And Publish to Quay
        env:
          DOCKER_REPO: kind-registry:5000/streamnativeio
          IMAGE_TAG_BASE: kind-registry:5000/streamnativeio/function-mesh
          CATALOG_BRANCH_TAG: latest
        run: |
          echo $VERSION
          make redhat-certificated-image-build redhat-certificated-image-push redhat-certificated-bundle redhat-certificated-bundle-build redhat-certificated-bundle-push catalog-build catalog-push 

      - name: Install the Operator Lifecycle Manager
        run: |
          operator-sdk olm install --version v0.21.2
          operator-sdk olm status
          kubectl get pods -n olm

      - name: Adding the catalog containing function mesh Operator
        run: |
          kubectl apply -f .ci/olm-tests/catalog.yml
          kubectl get catalogsource -n olm
          kubectl get catalogsource my-test-catalog -n olm -o yaml
          kubectl get pod -n olm
          sleep 60
          kubectl -n olm wait --for=condition=ready pod -l olm.catalogSource=my-test-catalog --timeout=600s
          kubectl get catalogsource my-test-catalog -n olm -o yaml

      - name: Create an OperatorGroup
        run: |
          kubectl apply -f .ci/olm-tests/operatorgroup.yml

      - name: Create a Subscription
        run: |
          kubectl apply -f .ci/olm-tests/subs.yml
          sleep 60

      - name: Verify Operator health
        run: |
          kubectl wait deployment/function-mesh-controller-manager --for=condition=Available --timeout=600s

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()
