name: Precommit - OLM verify
on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'PROJECT'
      - 'LICENSE'
      - 'mesh-worker-service/README.md'
      - 'tools/README.md'
jobs:
  olm-verify:
    name: Verify OLM bundle
    runs-on: ubuntu-latest
    steps:
      - name: clean disk
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h

      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up GO 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: InstallKubebuilder
        run: |
          curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin

      - name: Install operator-sdk
        run: |
          RELEASE_VERSION=v1.14.0
          curl -LO "https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk_linux_amd64"
          chmod +x operator-sdk_linux_amd64 && sudo mkdir -p /usr/local/bin/ && sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

      - name: Set up yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.6.0/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --help

      - name: build release
        id: build_release
        env:
          VERSION: ${{ github.event.release.tag_name }}
          IMAGE_TAG_BASE: streamnative/function-mesh
          CATALOG_BRANCH_TAG: latest
        run: |
          # convert vx.y.z to x.y.z because a valid semver is needed in creating the bundle
          VERSION=$(echo $VERSION|cut -c 2-)
          make release

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        with:
          node_image: kindest/node:v1.21.1

      - name: Build RedHat certificated bundle And Publish to Quay
        env:
          VERSION: ${{ github.event.release.tag_name }}
          DOCKER_REPO: kind-registry:5000/streamnativeio
          IMAGE_TAG_BASE: kind-registry:5000/streamnativeio/function-mesh
          CATALOG_BRANCH_TAG: latest
        run: |
          # convert vx.y.z to x.y.z because a valid semver is needed in creating the bundle
          VERSION=$(echo $VERSION|cut -c 2-)
          echo $VERSION
          make redhat-certificated-image-build redhat-certificated-image-push redhat-certificated-bundle redhat-certificated-bundle-build redhat-certificated-bundle-push

      - name: Install the Operator Lifecycle Manager
        run: |
          operator-sdk olm install
          operator-sdk olm status
          kubectl get pods -n olm

      - name: Adding the catalog containing function mesh Operator
        run: |
          kubectl apply -f .ci/olm-tests/catalog.yml
          kubectl get catalogsource -n olm
          kubectl get catalogsource my-test-catalog -n olm -o yaml
          kubectl get pod -n olm
          kubectl get packagemanifests | grep function-mesh

      - name: Create an OperatorGroup
        run: |
          kubectl apply -f .ci/olm-tests/operatorgroup.yml

      - name: Create a Subscription
        run: |
          kubectl apply -f .ci/olm-tests/subs.yaml

      - name: Verify Operator health
        run: |
          kubectl wait deployment/function-mesh-controller-manager --for=condition=Available --timeout=30s

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3


